version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  settings:
    govet:
      enable:
        - shadow
    misspell:
      locale: US
  enable:
    - govet
    - staticcheck
    - errchec
    - unconvert
    - unparam
    - unused
    - ineffassign
    - misspell
    - dupl
    - gocritic
