// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/jaswdr/faker/v2"
	models "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen"
	enums "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen/dbenums"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type AccountMod interface {
	Apply(context.Context, *AccountTemplate)
}

type AccountModFunc func(context.Context, *AccountTemplate)

func (f AccountModFunc) Apply(ctx context.Context, n *AccountTemplate) {
	f(ctx, n)
}

type AccountModSlice []AccountMod

func (mods AccountModSlice) Apply(ctx context.Context, n *AccountTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// AccountTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AccountTemplate struct {
	ID             func() uuid.UUID
	WorkspaceID    func() uuid.UUID
	Name           func() string
	AccountType    func() enums.AccountType
	InitialBalance func() decimal.Decimal

	r accountR
	f *Factory

	alreadyPersisted bool
}

type accountR struct {
	Workspace                *accountRWorkspaceR
	Transactions             []*accountRTransactionsR
	CounterpartyTransactions []*accountRCounterpartyTransactionsR
}

type accountRWorkspaceR struct {
	o *WorkspaceTemplate
}
type accountRTransactionsR struct {
	number int
	o      *TransactionTemplate
}
type accountRCounterpartyTransactionsR struct {
	number int
	o      *TransactionTemplate
}

// Apply mods to the AccountTemplate
func (o *AccountTemplate) Apply(ctx context.Context, mods ...AccountMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Account
// according to the relationships in the template. Nothing is inserted into the db
func (t AccountTemplate) setModelRels(o *models.Account) {
	if t.r.Workspace != nil {
		rel := t.r.Workspace.o.Build()
		rel.R.Accounts = append(rel.R.Accounts, o)
		o.WorkspaceID = rel.ID // h2
		o.R.Workspace = rel
	}

	if t.r.Transactions != nil {
		rel := models.TransactionSlice{}
		for _, r := range t.r.Transactions {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.WorkspaceID = o.WorkspaceID // h2
				rel.AccountID = null.From(o.ID) // h2
				rel.R.Account = o
			}
			rel = append(rel, related...)
		}
		o.R.Transactions = rel
	}

	if t.r.CounterpartyTransactions != nil {
		rel := models.TransactionSlice{}
		for _, r := range t.r.CounterpartyTransactions {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.WorkspaceID = o.WorkspaceID             // h2
				rel.CounterpartyAccountID = null.From(o.ID) // h2
				rel.R.CounterpartyAccount = o
			}
			rel = append(rel, related...)
		}
		o.R.CounterpartyTransactions = rel
	}
}

// BuildSetter returns an *models.AccountSetter
// this does nothing with the relationship templates
func (o AccountTemplate) BuildSetter() *models.AccountSetter {
	m := &models.AccountSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.WorkspaceID != nil {
		val := o.WorkspaceID()
		m.WorkspaceID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.AccountType != nil {
		val := o.AccountType()
		m.AccountType = omit.From(val)
	}
	if o.InitialBalance != nil {
		val := o.InitialBalance()
		m.InitialBalance = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.AccountSetter
// this does nothing with the relationship templates
func (o AccountTemplate) BuildManySetter(number int) []*models.AccountSetter {
	m := make([]*models.AccountSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Account
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AccountTemplate.Create
func (o AccountTemplate) Build() *models.Account {
	m := &models.Account{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.WorkspaceID != nil {
		m.WorkspaceID = o.WorkspaceID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.AccountType != nil {
		m.AccountType = o.AccountType()
	}
	if o.InitialBalance != nil {
		m.InitialBalance = o.InitialBalance()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AccountSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AccountTemplate.CreateMany
func (o AccountTemplate) BuildMany(number int) models.AccountSlice {
	m := make(models.AccountSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAccount(m *models.AccountSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.WorkspaceID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.WorkspaceID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.AccountType.IsValue()) {
		val := random_enums_AccountType(nil)
		m.AccountType = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Account
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AccountTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Account) error {
	var err error

	isTransactionsDone, _ := accountRelTransactionsCtx.Value(ctx)
	if !isTransactionsDone && o.r.Transactions != nil {
		ctx = accountRelTransactionsCtx.WithValue(ctx, true)
		for _, r := range o.r.Transactions {
			if r.o.alreadyPersisted {
				m.R.Transactions = append(m.R.Transactions, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachTransactions(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isCounterpartyTransactionsDone, _ := accountRelCounterpartyTransactionsCtx.Value(ctx)
	if !isCounterpartyTransactionsDone && o.r.CounterpartyTransactions != nil {
		ctx = accountRelCounterpartyTransactionsCtx.WithValue(ctx, true)
		for _, r := range o.r.CounterpartyTransactions {
			if r.o.alreadyPersisted {
				m.R.CounterpartyTransactions = append(m.R.CounterpartyTransactions, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCounterpartyTransactions(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a account and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AccountTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Account, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAccount(opt)

	if o.r.Workspace == nil {
		AccountMods.WithNewWorkspace().Apply(ctx, o)
	}

	var rel0 *models.Workspace

	if o.r.Workspace.o.alreadyPersisted {
		rel0 = o.r.Workspace.o.Build()
	} else {
		rel0, err = o.r.Workspace.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.WorkspaceID = omit.From(rel0.ID)

	m, err := models.Accounts.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Workspace = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a account and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AccountTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Account {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a account and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AccountTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Account {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple accounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AccountTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AccountSlice, error) {
	var err error
	m := make(models.AccountSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple accounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AccountTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AccountSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple accounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AccountTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AccountSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Account has methods that act as mods for the AccountTemplate
var AccountMods accountMods

type accountMods struct{}

func (m accountMods) RandomizeAllColumns(f *faker.Faker) AccountMod {
	return AccountModSlice{
		AccountMods.RandomID(f),
		AccountMods.RandomWorkspaceID(f),
		AccountMods.RandomName(f),
		AccountMods.RandomAccountType(f),
		AccountMods.RandomInitialBalance(f),
	}
}

// Set the model columns to this value
func (m accountMods) ID(val uuid.UUID) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m accountMods) IDFunc(f func() uuid.UUID) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetID() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomID(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m accountMods) WorkspaceID(val uuid.UUID) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.WorkspaceID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m accountMods) WorkspaceIDFunc(f func() uuid.UUID) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.WorkspaceID = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetWorkspaceID() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.WorkspaceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomWorkspaceID(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.WorkspaceID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m accountMods) Name(val string) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m accountMods) NameFunc(f func() string) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetName() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomName(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m accountMods) AccountType(val enums.AccountType) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.AccountType = func() enums.AccountType { return val }
	})
}

// Set the Column from the function
func (m accountMods) AccountTypeFunc(f func() enums.AccountType) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.AccountType = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetAccountType() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.AccountType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomAccountType(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.AccountType = func() enums.AccountType {
			return random_enums_AccountType(f)
		}
	})
}

// Set the model columns to this value
func (m accountMods) InitialBalance(val decimal.Decimal) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.InitialBalance = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m accountMods) InitialBalanceFunc(f func() decimal.Decimal) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.InitialBalance = f
	})
}

// Clear any values for the column
func (m accountMods) UnsetInitialBalance() AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.InitialBalance = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m accountMods) RandomInitialBalance(f *faker.Faker) AccountMod {
	return AccountModFunc(func(_ context.Context, o *AccountTemplate) {
		o.InitialBalance = func() decimal.Decimal {
			return random_decimal_Decimal(f, "14", "2")
		}
	})
}

func (m accountMods) WithParentsCascading() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		if isDone, _ := accountWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = accountWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewWorkspaceWithContext(ctx, WorkspaceMods.WithParentsCascading())
			m.WithWorkspace(related).Apply(ctx, o)
		}
	})
}

func (m accountMods) WithWorkspace(rel *WorkspaceTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Workspace = &accountRWorkspaceR{
			o: rel,
		}
	})
}

func (m accountMods) WithNewWorkspace(mods ...WorkspaceMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewWorkspaceWithContext(ctx, mods...)

		m.WithWorkspace(related).Apply(ctx, o)
	})
}

func (m accountMods) WithExistingWorkspace(em *models.Workspace) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Workspace = &accountRWorkspaceR{
			o: o.f.FromExistingWorkspace(em),
		}
	})
}

func (m accountMods) WithoutWorkspace() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Workspace = nil
	})
}

func (m accountMods) WithTransactions(number int, related *TransactionTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Transactions = []*accountRTransactionsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m accountMods) WithNewTransactions(number int, mods ...TransactionMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewTransactionWithContext(ctx, mods...)
		m.WithTransactions(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddTransactions(number int, related *TransactionTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Transactions = append(o.r.Transactions, &accountRTransactionsR{
			number: number,
			o:      related,
		})
	})
}

func (m accountMods) AddNewTransactions(number int, mods ...TransactionMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewTransactionWithContext(ctx, mods...)
		m.AddTransactions(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddExistingTransactions(existingModels ...*models.Transaction) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		for _, em := range existingModels {
			o.r.Transactions = append(o.r.Transactions, &accountRTransactionsR{
				o: o.f.FromExistingTransaction(em),
			})
		}
	})
}

func (m accountMods) WithoutTransactions() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.Transactions = nil
	})
}

func (m accountMods) WithCounterpartyTransactions(number int, related *TransactionTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.CounterpartyTransactions = []*accountRCounterpartyTransactionsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m accountMods) WithNewCounterpartyTransactions(number int, mods ...TransactionMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewTransactionWithContext(ctx, mods...)
		m.WithCounterpartyTransactions(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddCounterpartyTransactions(number int, related *TransactionTemplate) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.CounterpartyTransactions = append(o.r.CounterpartyTransactions, &accountRCounterpartyTransactionsR{
			number: number,
			o:      related,
		})
	})
}

func (m accountMods) AddNewCounterpartyTransactions(number int, mods ...TransactionMod) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		related := o.f.NewTransactionWithContext(ctx, mods...)
		m.AddCounterpartyTransactions(number, related).Apply(ctx, o)
	})
}

func (m accountMods) AddExistingCounterpartyTransactions(existingModels ...*models.Transaction) AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		for _, em := range existingModels {
			o.r.CounterpartyTransactions = append(o.r.CounterpartyTransactions, &accountRCounterpartyTransactionsR{
				o: o.f.FromExistingTransaction(em),
			})
		}
	})
}

func (m accountMods) WithoutCounterpartyTransactions() AccountMod {
	return AccountModFunc(func(ctx context.Context, o *AccountTemplate) {
		o.r.CounterpartyTransactions = nil
	})
}
