// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for accounts
	accountWithParentsCascadingCtx        = newContextual[bool]("accountWithParentsCascading")
	accountRelWorkspaceCtx                = newContextual[bool]("accounts.workspaces.accounts.fk_accounts_workspace")
	accountRelTransactionsCtx             = newContextual[bool]("accounts.transactions.transactions.fk_transactions_account")
	accountRelCounterpartyTransactionsCtx = newContextual[bool]("accounts.transactions.transactions.fk_transactions_counterparty_account")

	// Relationship Contexts for categories
	categoryWithParentsCascadingCtx = newContextual[bool]("categoryWithParentsCascading")
	categoryRelCategoryCtx          = newContextual[bool]("categories.categories.categories.fk_categories_parent")
	categoryRelReverseCategoriesCtx = newContextual[bool]("categories.categories.categories.fk_categories_parent")
	categoryRelWorkspaceCtx         = newContextual[bool]("categories.workspaces.categories.fk_categories_workspace")
	categoryRelTransactionsCtx      = newContextual[bool]("categories.transactions.transactions.fk_transactions_category")

	// Relationship Contexts for members
	memberWithParentsCascadingCtx = newContextual[bool]("memberWithParentsCascading")
	memberRelWorkspaceCtx         = newContextual[bool]("members.workspaces.members.fk_members_workspace")

	// Relationship Contexts for transactions
	transactionWithParentsCascadingCtx   = newContextual[bool]("transactionWithParentsCascading")
	transactionRelAccountCtx             = newContextual[bool]("accounts.transactions.transactions.fk_transactions_account")
	transactionRelCategoryCtx            = newContextual[bool]("categories.transactions.transactions.fk_transactions_category")
	transactionRelCounterpartyAccountCtx = newContextual[bool]("accounts.transactions.transactions.fk_transactions_counterparty_account")
	transactionRelWorkspaceCtx           = newContextual[bool]("transactions.workspaces.transactions.fk_transactions_workspace")

	// Relationship Contexts for workspaces
	workspaceWithParentsCascadingCtx = newContextual[bool]("workspaceWithParentsCascading")
	workspaceRelAccountsCtx          = newContextual[bool]("accounts.workspaces.accounts.fk_accounts_workspace")
	workspaceRelCategoriesCtx        = newContextual[bool]("categories.workspaces.categories.fk_categories_workspace")
	workspaceRelMembersCtx           = newContextual[bool]("members.workspaces.members.fk_members_workspace")
	workspaceRelTransactionsCtx      = newContextual[bool]("transactions.workspaces.transactions.fk_transactions_workspace")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
