// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/google/uuid"
	models "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen"
	enums "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen/dbenums"
	"github.com/shopspring/decimal"
)

type Factory struct {
	baseAccountMods     AccountModSlice
	baseCategoryMods    CategoryModSlice
	baseMemberMods      MemberModSlice
	baseTransactionMods TransactionModSlice
	baseWorkspaceMods   WorkspaceModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewAccount(mods ...AccountMod) *AccountTemplate {
	return f.NewAccountWithContext(context.Background(), mods...)
}

func (f *Factory) NewAccountWithContext(ctx context.Context, mods ...AccountMod) *AccountTemplate {
	o := &AccountTemplate{f: f}

	if f != nil {
		f.baseAccountMods.Apply(ctx, o)
	}

	AccountModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingAccount(m *models.Account) *AccountTemplate {
	o := &AccountTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.WorkspaceID = func() uuid.UUID { return m.WorkspaceID }
	o.Name = func() string { return m.Name }
	o.AccountType = func() enums.AccountType { return m.AccountType }
	o.InitialBalance = func() decimal.Decimal { return m.InitialBalance }

	ctx := context.Background()
	if m.R.Workspace != nil {
		AccountMods.WithExistingWorkspace(m.R.Workspace).Apply(ctx, o)
	}
	if len(m.R.Transactions) > 0 {
		AccountMods.AddExistingTransactions(m.R.Transactions...).Apply(ctx, o)
	}
	if len(m.R.CounterpartyTransactions) > 0 {
		AccountMods.AddExistingCounterpartyTransactions(m.R.CounterpartyTransactions...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewCategory(mods ...CategoryMod) *CategoryTemplate {
	return f.NewCategoryWithContext(context.Background(), mods...)
}

func (f *Factory) NewCategoryWithContext(ctx context.Context, mods ...CategoryMod) *CategoryTemplate {
	o := &CategoryTemplate{f: f}

	if f != nil {
		f.baseCategoryMods.Apply(ctx, o)
	}

	CategoryModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCategory(m *models.Category) *CategoryTemplate {
	o := &CategoryTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.WorkspaceID = func() uuid.UUID { return m.WorkspaceID }
	o.Name = func() string { return m.Name }
	o.CategoryType = func() enums.CategoryType { return m.CategoryType }
	o.ParentID = func() null.Val[uuid.UUID] { return m.ParentID }

	ctx := context.Background()
	if m.R.Category != nil {
		CategoryMods.WithExistingCategory(m.R.Category).Apply(ctx, o)
	}
	if len(m.R.ReverseCategories) > 0 {
		CategoryMods.AddExistingReverseCategories(m.R.ReverseCategories...).Apply(ctx, o)
	}
	if m.R.Workspace != nil {
		CategoryMods.WithExistingWorkspace(m.R.Workspace).Apply(ctx, o)
	}
	if len(m.R.Transactions) > 0 {
		CategoryMods.AddExistingTransactions(m.R.Transactions...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewMember(mods ...MemberMod) *MemberTemplate {
	return f.NewMemberWithContext(context.Background(), mods...)
}

func (f *Factory) NewMemberWithContext(ctx context.Context, mods ...MemberMod) *MemberTemplate {
	o := &MemberTemplate{f: f}

	if f != nil {
		f.baseMemberMods.Apply(ctx, o)
	}

	MemberModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingMember(m *models.Member) *MemberTemplate {
	o := &MemberTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.WorkspaceID = func() uuid.UUID { return m.WorkspaceID }
	o.Email = func() string { return m.Email }
	o.DisplayName = func() string { return m.DisplayName }
	o.Role = func() enums.MemberRole { return m.Role }

	ctx := context.Background()
	if m.R.Workspace != nil {
		MemberMods.WithExistingWorkspace(m.R.Workspace).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewTransaction(mods ...TransactionMod) *TransactionTemplate {
	return f.NewTransactionWithContext(context.Background(), mods...)
}

func (f *Factory) NewTransactionWithContext(ctx context.Context, mods ...TransactionMod) *TransactionTemplate {
	o := &TransactionTemplate{f: f}

	if f != nil {
		f.baseTransactionMods.Apply(ctx, o)
	}

	TransactionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingTransaction(m *models.Transaction) *TransactionTemplate {
	o := &TransactionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.WorkspaceID = func() uuid.UUID { return m.WorkspaceID }
	o.TransactionType = func() enums.TransactionType { return m.TransactionType }
	o.AccountID = func() null.Val[uuid.UUID] { return m.AccountID }
	o.CounterpartyAccountID = func() null.Val[uuid.UUID] { return m.CounterpartyAccountID }
	o.CategoryID = func() null.Val[uuid.UUID] { return m.CategoryID }
	o.Amount = func() decimal.Decimal { return m.Amount }
	o.OccurredAt = func() time.Time { return m.OccurredAt }
	o.Description = func() null.Val[string] { return m.Description }

	ctx := context.Background()
	if m.R.Account != nil {
		TransactionMods.WithExistingAccount(m.R.Account).Apply(ctx, o)
	}
	if m.R.Category != nil {
		TransactionMods.WithExistingCategory(m.R.Category).Apply(ctx, o)
	}
	if m.R.CounterpartyAccount != nil {
		TransactionMods.WithExistingCounterpartyAccount(m.R.CounterpartyAccount).Apply(ctx, o)
	}
	if m.R.Workspace != nil {
		TransactionMods.WithExistingWorkspace(m.R.Workspace).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewWorkspace(mods ...WorkspaceMod) *WorkspaceTemplate {
	return f.NewWorkspaceWithContext(context.Background(), mods...)
}

func (f *Factory) NewWorkspaceWithContext(ctx context.Context, mods ...WorkspaceMod) *WorkspaceTemplate {
	o := &WorkspaceTemplate{f: f}

	if f != nil {
		f.baseWorkspaceMods.Apply(ctx, o)
	}

	WorkspaceModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingWorkspace(m *models.Workspace) *WorkspaceTemplate {
	o := &WorkspaceTemplate{f: f, alreadyPersisted: true}

	o.ID = func() uuid.UUID { return m.ID }
	o.Name = func() string { return m.Name }

	ctx := context.Background()
	if len(m.R.Accounts) > 0 {
		WorkspaceMods.AddExistingAccounts(m.R.Accounts...).Apply(ctx, o)
	}
	if len(m.R.Categories) > 0 {
		WorkspaceMods.AddExistingCategories(m.R.Categories...).Apply(ctx, o)
	}
	if len(m.R.Members) > 0 {
		WorkspaceMods.AddExistingMembers(m.R.Members...).Apply(ctx, o)
	}
	if len(m.R.Transactions) > 0 {
		WorkspaceMods.AddExistingTransactions(m.R.Transactions...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseAccountMods() {
	f.baseAccountMods = nil
}

func (f *Factory) AddBaseAccountMod(mods ...AccountMod) {
	f.baseAccountMods = append(f.baseAccountMods, mods...)
}

func (f *Factory) ClearBaseCategoryMods() {
	f.baseCategoryMods = nil
}

func (f *Factory) AddBaseCategoryMod(mods ...CategoryMod) {
	f.baseCategoryMods = append(f.baseCategoryMods, mods...)
}

func (f *Factory) ClearBaseMemberMods() {
	f.baseMemberMods = nil
}

func (f *Factory) AddBaseMemberMod(mods ...MemberMod) {
	f.baseMemberMods = append(f.baseMemberMods, mods...)
}

func (f *Factory) ClearBaseTransactionMods() {
	f.baseTransactionMods = nil
}

func (f *Factory) AddBaseTransactionMod(mods ...TransactionMod) {
	f.baseTransactionMods = append(f.baseTransactionMods, mods...)
}

func (f *Factory) ClearBaseWorkspaceMods() {
	f.baseWorkspaceMods = nil
}

func (f *Factory) AddBaseWorkspaceMod(mods ...WorkspaceMod) {
	f.baseWorkspaceMods = append(f.baseWorkspaceMods, mods...)
}
