// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/jaswdr/faker/v2"
	models "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen"
	enums "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen/dbenums"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type TransactionMod interface {
	Apply(context.Context, *TransactionTemplate)
}

type TransactionModFunc func(context.Context, *TransactionTemplate)

func (f TransactionModFunc) Apply(ctx context.Context, n *TransactionTemplate) {
	f(ctx, n)
}

type TransactionModSlice []TransactionMod

func (mods TransactionModSlice) Apply(ctx context.Context, n *TransactionTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// TransactionTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type TransactionTemplate struct {
	ID                    func() uuid.UUID
	WorkspaceID           func() uuid.UUID
	TransactionType       func() enums.TransactionType
	AccountID             func() null.Val[uuid.UUID]
	CounterpartyAccountID func() null.Val[uuid.UUID]
	CategoryID            func() null.Val[uuid.UUID]
	Amount                func() decimal.Decimal
	OccurredAt            func() time.Time
	Description           func() null.Val[string]

	r transactionR
	f *Factory

	alreadyPersisted bool
}

type transactionR struct {
	Account             *transactionRAccountR
	Category            *transactionRCategoryR
	CounterpartyAccount *transactionRCounterpartyAccountR
	Workspace           *transactionRWorkspaceR
}

type transactionRAccountR struct {
	o *AccountTemplate
}
type transactionRCategoryR struct {
	o *CategoryTemplate
}
type transactionRCounterpartyAccountR struct {
	o *AccountTemplate
}
type transactionRWorkspaceR struct {
	o *WorkspaceTemplate
}

// Apply mods to the TransactionTemplate
func (o *TransactionTemplate) Apply(ctx context.Context, mods ...TransactionMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Transaction
// according to the relationships in the template. Nothing is inserted into the db
func (t TransactionTemplate) setModelRels(o *models.Transaction) {
	if t.r.Account != nil {
		rel := t.r.Account.o.Build()
		rel.R.Transactions = append(rel.R.Transactions, o)
		o.WorkspaceID = rel.WorkspaceID // h2
		o.AccountID = null.From(rel.ID) // h2
		o.R.Account = rel
	}

	if t.r.Category != nil {
		rel := t.r.Category.o.Build()
		rel.R.Transactions = append(rel.R.Transactions, o)
		o.WorkspaceID = rel.WorkspaceID  // h2
		o.CategoryID = null.From(rel.ID) // h2
		o.R.Category = rel
	}

	if t.r.CounterpartyAccount != nil {
		rel := t.r.CounterpartyAccount.o.Build()
		rel.R.CounterpartyTransactions = append(rel.R.CounterpartyTransactions, o)
		o.WorkspaceID = rel.WorkspaceID             // h2
		o.CounterpartyAccountID = null.From(rel.ID) // h2
		o.R.CounterpartyAccount = rel
	}

	if t.r.Workspace != nil {
		rel := t.r.Workspace.o.Build()
		rel.R.Transactions = append(rel.R.Transactions, o)
		o.WorkspaceID = rel.ID // h2
		o.R.Workspace = rel
	}
}

// BuildSetter returns an *models.TransactionSetter
// this does nothing with the relationship templates
func (o TransactionTemplate) BuildSetter() *models.TransactionSetter {
	m := &models.TransactionSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.WorkspaceID != nil {
		val := o.WorkspaceID()
		m.WorkspaceID = omit.From(val)
	}
	if o.TransactionType != nil {
		val := o.TransactionType()
		m.TransactionType = omit.From(val)
	}
	if o.AccountID != nil {
		val := o.AccountID()
		m.AccountID = omitnull.FromNull(val)
	}
	if o.CounterpartyAccountID != nil {
		val := o.CounterpartyAccountID()
		m.CounterpartyAccountID = omitnull.FromNull(val)
	}
	if o.CategoryID != nil {
		val := o.CategoryID()
		m.CategoryID = omitnull.FromNull(val)
	}
	if o.Amount != nil {
		val := o.Amount()
		m.Amount = omit.From(val)
	}
	if o.OccurredAt != nil {
		val := o.OccurredAt()
		m.OccurredAt = omit.From(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.TransactionSetter
// this does nothing with the relationship templates
func (o TransactionTemplate) BuildManySetter(number int) []*models.TransactionSetter {
	m := make([]*models.TransactionSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Transaction
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TransactionTemplate.Create
func (o TransactionTemplate) Build() *models.Transaction {
	m := &models.Transaction{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.WorkspaceID != nil {
		m.WorkspaceID = o.WorkspaceID()
	}
	if o.TransactionType != nil {
		m.TransactionType = o.TransactionType()
	}
	if o.AccountID != nil {
		m.AccountID = o.AccountID()
	}
	if o.CounterpartyAccountID != nil {
		m.CounterpartyAccountID = o.CounterpartyAccountID()
	}
	if o.CategoryID != nil {
		m.CategoryID = o.CategoryID()
	}
	if o.Amount != nil {
		m.Amount = o.Amount()
	}
	if o.OccurredAt != nil {
		m.OccurredAt = o.OccurredAt()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.TransactionSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TransactionTemplate.CreateMany
func (o TransactionTemplate) BuildMany(number int) models.TransactionSlice {
	m := make(models.TransactionSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableTransaction(m *models.TransactionSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.WorkspaceID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.WorkspaceID = omit.From(val)
	}
	if !(m.TransactionType.IsValue()) {
		val := random_enums_TransactionType(nil)
		m.TransactionType = omit.From(val)
	}
	if !(m.Amount.IsValue()) {
		val := random_decimal_Decimal(nil, "14", "2")
		m.Amount = omit.From(val)
	}
	if !(m.OccurredAt.IsValue()) {
		val := random_time_Time(nil)
		m.OccurredAt = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Transaction
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *TransactionTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Transaction) error {
	var err error

	return err
}

// Create builds a transaction and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *TransactionTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Transaction, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableTransaction(opt)

	if o.r.Account == nil {
		TransactionMods.WithNewAccount().Apply(ctx, o)
	}

	var rel0 *models.Account

	if o.r.Account.o.alreadyPersisted {
		rel0 = o.r.Account.o.Build()
	} else {
		rel0, err = o.r.Account.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.WorkspaceID = omit.From(rel0.WorkspaceID)
	opt.AccountID = omitnull.From(rel0.ID)

	if o.r.Category == nil {
		TransactionMods.WithNewCategory().Apply(ctx, o)
	}

	var rel1 *models.Category

	if o.r.Category.o.alreadyPersisted {
		rel1 = o.r.Category.o.Build()
	} else {
		rel1, err = o.r.Category.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.WorkspaceID = omit.From(rel1.WorkspaceID)
	opt.CategoryID = omitnull.From(rel1.ID)

	if o.r.CounterpartyAccount == nil {
		TransactionMods.WithNewCounterpartyAccount().Apply(ctx, o)
	}

	var rel2 *models.Account

	if o.r.CounterpartyAccount.o.alreadyPersisted {
		rel2 = o.r.CounterpartyAccount.o.Build()
	} else {
		rel2, err = o.r.CounterpartyAccount.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.WorkspaceID = omit.From(rel2.WorkspaceID)
	opt.CounterpartyAccountID = omitnull.From(rel2.ID)

	if o.r.Workspace == nil {
		TransactionMods.WithNewWorkspace().Apply(ctx, o)
	}

	var rel3 *models.Workspace

	if o.r.Workspace.o.alreadyPersisted {
		rel3 = o.r.Workspace.o.Build()
	} else {
		rel3, err = o.r.Workspace.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.WorkspaceID = omit.From(rel3.ID)

	m, err := models.Transactions.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Account = rel0
	m.R.Category = rel1
	m.R.CounterpartyAccount = rel2
	m.R.Workspace = rel3

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a transaction and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *TransactionTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Transaction {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a transaction and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *TransactionTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Transaction {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple transactions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o TransactionTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.TransactionSlice, error) {
	var err error
	m := make(models.TransactionSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple transactions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o TransactionTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.TransactionSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple transactions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o TransactionTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.TransactionSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Transaction has methods that act as mods for the TransactionTemplate
var TransactionMods transactionMods

type transactionMods struct{}

func (m transactionMods) RandomizeAllColumns(f *faker.Faker) TransactionMod {
	return TransactionModSlice{
		TransactionMods.RandomID(f),
		TransactionMods.RandomWorkspaceID(f),
		TransactionMods.RandomTransactionType(f),
		TransactionMods.RandomAccountID(f),
		TransactionMods.RandomCounterpartyAccountID(f),
		TransactionMods.RandomCategoryID(f),
		TransactionMods.RandomAmount(f),
		TransactionMods.RandomOccurredAt(f),
		TransactionMods.RandomDescription(f),
	}
}

// Set the model columns to this value
func (m transactionMods) ID(val uuid.UUID) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m transactionMods) IDFunc(f func() uuid.UUID) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetID() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m transactionMods) RandomID(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m transactionMods) WorkspaceID(val uuid.UUID) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.WorkspaceID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m transactionMods) WorkspaceIDFunc(f func() uuid.UUID) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.WorkspaceID = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetWorkspaceID() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.WorkspaceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m transactionMods) RandomWorkspaceID(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.WorkspaceID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m transactionMods) TransactionType(val enums.TransactionType) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.TransactionType = func() enums.TransactionType { return val }
	})
}

// Set the Column from the function
func (m transactionMods) TransactionTypeFunc(f func() enums.TransactionType) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.TransactionType = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetTransactionType() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.TransactionType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m transactionMods) RandomTransactionType(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.TransactionType = func() enums.TransactionType {
			return random_enums_TransactionType(f)
		}
	})
}

// Set the model columns to this value
func (m transactionMods) AccountID(val null.Val[uuid.UUID]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.AccountID = func() null.Val[uuid.UUID] { return val }
	})
}

// Set the Column from the function
func (m transactionMods) AccountIDFunc(f func() null.Val[uuid.UUID]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.AccountID = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetAccountID() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.AccountID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m transactionMods) RandomAccountID(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.AccountID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m transactionMods) RandomAccountIDNotNull(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.AccountID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m transactionMods) CounterpartyAccountID(val null.Val[uuid.UUID]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CounterpartyAccountID = func() null.Val[uuid.UUID] { return val }
	})
}

// Set the Column from the function
func (m transactionMods) CounterpartyAccountIDFunc(f func() null.Val[uuid.UUID]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CounterpartyAccountID = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetCounterpartyAccountID() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CounterpartyAccountID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m transactionMods) RandomCounterpartyAccountID(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CounterpartyAccountID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m transactionMods) RandomCounterpartyAccountIDNotNull(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CounterpartyAccountID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m transactionMods) CategoryID(val null.Val[uuid.UUID]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CategoryID = func() null.Val[uuid.UUID] { return val }
	})
}

// Set the Column from the function
func (m transactionMods) CategoryIDFunc(f func() null.Val[uuid.UUID]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CategoryID = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetCategoryID() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CategoryID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m transactionMods) RandomCategoryID(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CategoryID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m transactionMods) RandomCategoryIDNotNull(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.CategoryID = func() null.Val[uuid.UUID] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_uuid_UUID(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m transactionMods) Amount(val decimal.Decimal) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Amount = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m transactionMods) AmountFunc(f func() decimal.Decimal) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Amount = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetAmount() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Amount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m transactionMods) RandomAmount(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Amount = func() decimal.Decimal {
			return random_decimal_Decimal(f, "14", "2")
		}
	})
}

// Set the model columns to this value
func (m transactionMods) OccurredAt(val time.Time) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.OccurredAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m transactionMods) OccurredAtFunc(f func() time.Time) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.OccurredAt = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetOccurredAt() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.OccurredAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m transactionMods) RandomOccurredAt(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.OccurredAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m transactionMods) Description(val null.Val[string]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Description = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m transactionMods) DescriptionFunc(f func() null.Val[string]) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m transactionMods) UnsetDescription() TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m transactionMods) RandomDescription(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m transactionMods) RandomDescriptionNotNull(f *faker.Faker) TransactionMod {
	return TransactionModFunc(func(_ context.Context, o *TransactionTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m transactionMods) WithParentsCascading() TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		if isDone, _ := transactionWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = transactionWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewAccountWithContext(ctx, AccountMods.WithParentsCascading())
			m.WithAccount(related).Apply(ctx, o)
		}
		{

			related := o.f.NewCategoryWithContext(ctx, CategoryMods.WithParentsCascading())
			m.WithCategory(related).Apply(ctx, o)
		}
		{

			related := o.f.NewAccountWithContext(ctx, AccountMods.WithParentsCascading())
			m.WithCounterpartyAccount(related).Apply(ctx, o)
		}
		{

			related := o.f.NewWorkspaceWithContext(ctx, WorkspaceMods.WithParentsCascading())
			m.WithWorkspace(related).Apply(ctx, o)
		}
	})
}

func (m transactionMods) WithAccount(rel *AccountTemplate) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Account = &transactionRAccountR{
			o: rel,
		}
	})
}

func (m transactionMods) WithNewAccount(mods ...AccountMod) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		related := o.f.NewAccountWithContext(ctx, mods...)

		m.WithAccount(related).Apply(ctx, o)
	})
}

func (m transactionMods) WithExistingAccount(em *models.Account) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Account = &transactionRAccountR{
			o: o.f.FromExistingAccount(em),
		}
	})
}

func (m transactionMods) WithoutAccount() TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Account = nil
	})
}

func (m transactionMods) WithCategory(rel *CategoryTemplate) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Category = &transactionRCategoryR{
			o: rel,
		}
	})
}

func (m transactionMods) WithNewCategory(mods ...CategoryMod) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		related := o.f.NewCategoryWithContext(ctx, mods...)

		m.WithCategory(related).Apply(ctx, o)
	})
}

func (m transactionMods) WithExistingCategory(em *models.Category) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Category = &transactionRCategoryR{
			o: o.f.FromExistingCategory(em),
		}
	})
}

func (m transactionMods) WithoutCategory() TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Category = nil
	})
}

func (m transactionMods) WithCounterpartyAccount(rel *AccountTemplate) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.CounterpartyAccount = &transactionRCounterpartyAccountR{
			o: rel,
		}
	})
}

func (m transactionMods) WithNewCounterpartyAccount(mods ...AccountMod) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		related := o.f.NewAccountWithContext(ctx, mods...)

		m.WithCounterpartyAccount(related).Apply(ctx, o)
	})
}

func (m transactionMods) WithExistingCounterpartyAccount(em *models.Account) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.CounterpartyAccount = &transactionRCounterpartyAccountR{
			o: o.f.FromExistingAccount(em),
		}
	})
}

func (m transactionMods) WithoutCounterpartyAccount() TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.CounterpartyAccount = nil
	})
}

func (m transactionMods) WithWorkspace(rel *WorkspaceTemplate) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Workspace = &transactionRWorkspaceR{
			o: rel,
		}
	})
}

func (m transactionMods) WithNewWorkspace(mods ...WorkspaceMod) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		related := o.f.NewWorkspaceWithContext(ctx, mods...)

		m.WithWorkspace(related).Apply(ctx, o)
	})
}

func (m transactionMods) WithExistingWorkspace(em *models.Workspace) TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Workspace = &transactionRWorkspaceR{
			o: o.f.FromExistingWorkspace(em),
		}
	})
}

func (m transactionMods) WithoutWorkspace() TransactionMod {
	return TransactionModFunc(func(ctx context.Context, o *TransactionTemplate) {
		o.r.Workspace = nil
	})
}
