// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreateAccountParams is parameters of createAccount operation.
type CreateAccountParams struct {
	WsId uuid.UUID
}

func unpackCreateAccountParams(packed middleware.Parameters) (params CreateAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateAccountParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateAccountParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateCategoryParams is parameters of createCategory operation.
type CreateCategoryParams struct {
	WsId uuid.UUID
}

func unpackCreateCategoryParams(packed middleware.Parameters) (params CreateCategoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateCategoryParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateCategoryParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateMemberParams is parameters of createMember operation.
type CreateMemberParams struct {
	WsId uuid.UUID
}

func unpackCreateMemberParams(packed middleware.Parameters) (params CreateMemberParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateMemberParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateMemberParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateTransactionParams is parameters of createTransaction operation.
type CreateTransactionParams struct {
	WsId uuid.UUID
}

func unpackCreateTransactionParams(packed middleware.Parameters) (params CreateTransactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateTransactionParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateTransactionParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteAccountParams is parameters of deleteAccount operation.
type DeleteAccountParams struct {
	WsId      uuid.UUID
	AccountId uuid.UUID
}

func unpackDeleteAccountParams(packed middleware.Parameters) (params DeleteAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "accountId",
			In:   "path",
		}
		params.AccountId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteAccountParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteAccountParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: accountId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AccountId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteCategoryParams is parameters of deleteCategory operation.
type DeleteCategoryParams struct {
	WsId       uuid.UUID
	CategoryId uuid.UUID
}

func unpackDeleteCategoryParams(packed middleware.Parameters) (params DeleteCategoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "categoryId",
			In:   "path",
		}
		params.CategoryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteCategoryParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteCategoryParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: categoryId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "categoryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CategoryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "categoryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteMemberParams is parameters of deleteMember operation.
type DeleteMemberParams struct {
	WsId     uuid.UUID
	MemberId uuid.UUID
}

func unpackDeleteMemberParams(packed middleware.Parameters) (params DeleteMemberParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "memberId",
			In:   "path",
		}
		params.MemberId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteMemberParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteMemberParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: memberId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "memberId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.MemberId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "memberId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteTransactionParams is parameters of deleteTransaction operation.
type DeleteTransactionParams struct {
	WsId uuid.UUID
	TxId uuid.UUID
}

func unpackDeleteTransactionParams(packed middleware.Parameters) (params DeleteTransactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "txId",
			In:   "path",
		}
		params.TxId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteTransactionParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteTransactionParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: txId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "txId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TxId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "txId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteWorkspaceParams is parameters of deleteWorkspace operation.
type DeleteWorkspaceParams struct {
	WsId uuid.UUID
}

func unpackDeleteWorkspaceParams(packed middleware.Parameters) (params DeleteWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteWorkspaceParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAccountParams is parameters of getAccount operation.
type GetAccountParams struct {
	WsId      uuid.UUID
	AccountId uuid.UUID
}

func unpackGetAccountParams(packed middleware.Parameters) (params GetAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "accountId",
			In:   "path",
		}
		params.AccountId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetAccountParams(args [2]string, argsEscaped bool, r *http.Request) (params GetAccountParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: accountId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AccountId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAccountBalancesParams is parameters of getAccountBalances operation.
type GetAccountBalancesParams struct {
	AsOf time.Time
	WsId uuid.UUID
}

func unpackGetAccountBalancesParams(packed middleware.Parameters) (params GetAccountBalancesParams) {
	{
		key := middleware.ParameterKey{
			Name: "asOf",
			In:   "query",
		}
		params.AsOf = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetAccountBalancesParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAccountBalancesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: asOf.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "asOf",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.AsOf = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "asOf",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCategoryParams is parameters of getCategory operation.
type GetCategoryParams struct {
	WsId       uuid.UUID
	CategoryId uuid.UUID
}

func unpackGetCategoryParams(packed middleware.Parameters) (params GetCategoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "categoryId",
			In:   "path",
		}
		params.CategoryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetCategoryParams(args [2]string, argsEscaped bool, r *http.Request) (params GetCategoryParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: categoryId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "categoryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CategoryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "categoryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCategoryExpensesParams is parameters of getCategoryExpenses operation.
type GetCategoryExpensesParams struct {
	From time.Time
	To   time.Time
	WsId uuid.UUID
}

func unpackGetCategoryExpensesParams(packed middleware.Parameters) (params GetCategoryExpensesParams) {
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		params.From = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "to",
			In:   "query",
		}
		params.To = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetCategoryExpensesParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCategoryExpensesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.From = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: to.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.To = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "to",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDashboardParams is parameters of getDashboard operation.
type GetDashboardParams struct {
	From time.Time
	To   time.Time
	WsId uuid.UUID
}

func unpackGetDashboardParams(packed middleware.Parameters) (params GetDashboardParams) {
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		params.From = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "to",
			In:   "query",
		}
		params.To = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetDashboardParams(args [1]string, argsEscaped bool, r *http.Request) (params GetDashboardParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.From = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: to.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.To = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "to",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetMemberParams is parameters of getMember operation.
type GetMemberParams struct {
	WsId     uuid.UUID
	MemberId uuid.UUID
}

func unpackGetMemberParams(packed middleware.Parameters) (params GetMemberParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "memberId",
			In:   "path",
		}
		params.MemberId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetMemberParams(args [2]string, argsEscaped bool, r *http.Request) (params GetMemberParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: memberId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "memberId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.MemberId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "memberId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTransactionParams is parameters of getTransaction operation.
type GetTransactionParams struct {
	WsId uuid.UUID
	TxId uuid.UUID
}

func unpackGetTransactionParams(packed middleware.Parameters) (params GetTransactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "txId",
			In:   "path",
		}
		params.TxId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetTransactionParams(args [2]string, argsEscaped bool, r *http.Request) (params GetTransactionParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: txId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "txId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TxId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "txId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetWorkspaceParams is parameters of getWorkspace operation.
type GetWorkspaceParams struct {
	WsId uuid.UUID
}

func unpackGetWorkspaceParams(packed middleware.Parameters) (params GetWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetWorkspaceParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListAccountsParams is parameters of listAccounts operation.
type ListAccountsParams struct {
	WsId uuid.UUID
}

func unpackListAccountsParams(packed middleware.Parameters) (params ListAccountsParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeListAccountsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListAccountsParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListCategoriesParams is parameters of listCategories operation.
type ListCategoriesParams struct {
	WsId uuid.UUID
}

func unpackListCategoriesParams(packed middleware.Parameters) (params ListCategoriesParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeListCategoriesParams(args [1]string, argsEscaped bool, r *http.Request) (params ListCategoriesParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListMembersParams is parameters of listMembers operation.
type ListMembersParams struct {
	WsId uuid.UUID
}

func unpackListMembersParams(packed middleware.Parameters) (params ListMembersParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeListMembersParams(args [1]string, argsEscaped bool, r *http.Request) (params ListMembersParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListTransactionsParams is parameters of listTransactions operation.
type ListTransactionsParams struct {
	From OptDateTime `json:",omitempty,omitzero"`
	To   OptDateTime `json:",omitempty,omitzero"`
	WsId uuid.UUID
}

func unpackListTransactionsParams(packed middleware.Parameters) (params ListTransactionsParams) {
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.From = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "to",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.To = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeListTransactionsParams(args [1]string, argsEscaped bool, r *http.Request) (params ListTransactionsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFromVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotFromVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.From.SetTo(paramsDotFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: to.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotToVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotToVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.To.SetTo(paramsDotToVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "to",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateAccountParams is parameters of updateAccount operation.
type UpdateAccountParams struct {
	WsId      uuid.UUID
	AccountId uuid.UUID
}

func unpackUpdateAccountParams(packed middleware.Parameters) (params UpdateAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "accountId",
			In:   "path",
		}
		params.AccountId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateAccountParams(args [2]string, argsEscaped bool, r *http.Request) (params UpdateAccountParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: accountId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AccountId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateCategoryParams is parameters of updateCategory operation.
type UpdateCategoryParams struct {
	WsId       uuid.UUID
	CategoryId uuid.UUID
}

func unpackUpdateCategoryParams(packed middleware.Parameters) (params UpdateCategoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "categoryId",
			In:   "path",
		}
		params.CategoryId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateCategoryParams(args [2]string, argsEscaped bool, r *http.Request) (params UpdateCategoryParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: categoryId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "categoryId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CategoryId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "categoryId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateMemberParams is parameters of updateMember operation.
type UpdateMemberParams struct {
	WsId     uuid.UUID
	MemberId uuid.UUID
}

func unpackUpdateMemberParams(packed middleware.Parameters) (params UpdateMemberParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "memberId",
			In:   "path",
		}
		params.MemberId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateMemberParams(args [2]string, argsEscaped bool, r *http.Request) (params UpdateMemberParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: memberId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "memberId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.MemberId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "memberId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateTransactionParams is parameters of updateTransaction operation.
type UpdateTransactionParams struct {
	WsId uuid.UUID
	TxId uuid.UUID
}

func unpackUpdateTransactionParams(packed middleware.Parameters) (params UpdateTransactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "txId",
			In:   "path",
		}
		params.TxId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateTransactionParams(args [2]string, argsEscaped bool, r *http.Request) (params UpdateTransactionParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: txId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "txId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TxId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "txId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateWorkspaceParams is parameters of updateWorkspace operation.
type UpdateWorkspaceParams struct {
	WsId uuid.UUID
}

func unpackUpdateWorkspaceParams(packed middleware.Parameters) (params UpdateWorkspaceParams) {
	{
		key := middleware.ParameterKey{
			Name: "wsId",
			In:   "path",
		}
		params.WsId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateWorkspaceParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateWorkspaceParams, _ error) {
	// Decode path: wsId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "wsId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WsId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "wsId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
