// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/workspaces"

			if l := len("/workspaces"); len(elem) >= l && elem[0:l] == "/workspaces" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch r.Method {
				case "GET":
					s.handleListWorkspacesRequest([0]string{}, elemIsEscaped, w, r)
				case "POST":
					s.handleCreateWorkspaceRequest([0]string{}, elemIsEscaped, w, r)
				default:
					s.notAllowed(w, r, "GET,POST")
				}

				return
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "wsId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					switch r.Method {
					case "DELETE":
						s.handleDeleteWorkspaceRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					case "GET":
						s.handleGetWorkspaceRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					case "PUT":
						s.handleUpdateWorkspaceRequest([1]string{
							args[0],
						}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "DELETE,GET,PUT")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "accounts"

						if l := len("accounts"); len(elem) >= l && elem[0:l] == "accounts" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListAccountsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "POST":
								s.handleCreateAccountRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "accountId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleDeleteAccountRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetAccountRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleUpdateAccountRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,GET,PUT")
								}

								return
							}

						}

					case 'c': // Prefix: "categories"

						if l := len("categories"); len(elem) >= l && elem[0:l] == "categories" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListCategoriesRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "POST":
								s.handleCreateCategoryRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "categoryId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleDeleteCategoryRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetCategoryRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleUpdateCategoryRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,GET,PUT")
								}

								return
							}

						}

					case 'm': // Prefix: "members"

						if l := len("members"); len(elem) >= l && elem[0:l] == "members" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListMembersRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "POST":
								s.handleCreateMemberRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "memberId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleDeleteMemberRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetMemberRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleUpdateMemberRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,GET,PUT")
								}

								return
							}

						}

					case 'r': // Prefix: "reports/"

						if l := len("reports/"); len(elem) >= l && elem[0:l] == "reports/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "account-balances"

							if l := len("account-balances"); len(elem) >= l && elem[0:l] == "account-balances" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetAccountBalancesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'c': // Prefix: "category-expenses"

							if l := len("category-expenses"); len(elem) >= l && elem[0:l] == "category-expenses" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetCategoryExpensesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'd': // Prefix: "dashboard"

							if l := len("dashboard"); len(elem) >= l && elem[0:l] == "dashboard" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetDashboardRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						}

					case 't': // Prefix: "transactions"

						if l := len("transactions"); len(elem) >= l && elem[0:l] == "transactions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListTransactionsRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "POST":
								s.handleCreateTransactionRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "txId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleDeleteTransactionRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetTransactionRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleUpdateTransactionRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,GET,PUT")
								}

								return
							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/workspaces"

			if l := len("/workspaces"); len(elem) >= l && elem[0:l] == "/workspaces" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				switch method {
				case "GET":
					r.name = ListWorkspacesOperation
					r.summary = "ワークスペース一覧取得"
					r.operationID = "listWorkspaces"
					r.pathPattern = "/workspaces"
					r.args = args
					r.count = 0
					return r, true
				case "POST":
					r.name = CreateWorkspaceOperation
					r.summary = "ワークスペース作成"
					r.operationID = "createWorkspace"
					r.pathPattern = "/workspaces"
					r.args = args
					r.count = 0
					return r, true
				default:
					return
				}
			}
			switch elem[0] {
			case '/': // Prefix: "/"

				if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
					elem = elem[l:]
				} else {
					break
				}

				// Param: "wsId"
				// Match until "/"
				idx := strings.IndexByte(elem, '/')
				if idx < 0 {
					idx = len(elem)
				}
				args[0] = elem[:idx]
				elem = elem[idx:]

				if len(elem) == 0 {
					switch method {
					case "DELETE":
						r.name = DeleteWorkspaceOperation
						r.summary = "ワークスペース削除"
						r.operationID = "deleteWorkspace"
						r.pathPattern = "/workspaces/{wsId}"
						r.args = args
						r.count = 1
						return r, true
					case "GET":
						r.name = GetWorkspaceOperation
						r.summary = "ワークスペース詳細取得"
						r.operationID = "getWorkspace"
						r.pathPattern = "/workspaces/{wsId}"
						r.args = args
						r.count = 1
						return r, true
					case "PUT":
						r.name = UpdateWorkspaceOperation
						r.summary = "ワークスペース更新"
						r.operationID = "updateWorkspace"
						r.pathPattern = "/workspaces/{wsId}"
						r.args = args
						r.count = 1
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "accounts"

						if l := len("accounts"); len(elem) >= l && elem[0:l] == "accounts" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListAccountsOperation
								r.summary = "口座一覧取得"
								r.operationID = "listAccounts"
								r.pathPattern = "/workspaces/{wsId}/accounts"
								r.args = args
								r.count = 1
								return r, true
							case "POST":
								r.name = CreateAccountOperation
								r.summary = "口座作成"
								r.operationID = "createAccount"
								r.pathPattern = "/workspaces/{wsId}/accounts"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "accountId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = DeleteAccountOperation
									r.summary = "口座削除"
									r.operationID = "deleteAccount"
									r.pathPattern = "/workspaces/{wsId}/accounts/{accountId}"
									r.args = args
									r.count = 2
									return r, true
								case "GET":
									r.name = GetAccountOperation
									r.summary = "口座詳細取得"
									r.operationID = "getAccount"
									r.pathPattern = "/workspaces/{wsId}/accounts/{accountId}"
									r.args = args
									r.count = 2
									return r, true
								case "PUT":
									r.name = UpdateAccountOperation
									r.summary = "口座更新"
									r.operationID = "updateAccount"
									r.pathPattern = "/workspaces/{wsId}/accounts/{accountId}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'c': // Prefix: "categories"

						if l := len("categories"); len(elem) >= l && elem[0:l] == "categories" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListCategoriesOperation
								r.summary = "カテゴリ一覧取得"
								r.operationID = "listCategories"
								r.pathPattern = "/workspaces/{wsId}/categories"
								r.args = args
								r.count = 1
								return r, true
							case "POST":
								r.name = CreateCategoryOperation
								r.summary = "カテゴリ作成"
								r.operationID = "createCategory"
								r.pathPattern = "/workspaces/{wsId}/categories"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "categoryId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = DeleteCategoryOperation
									r.summary = "カテゴリ削除"
									r.operationID = "deleteCategory"
									r.pathPattern = "/workspaces/{wsId}/categories/{categoryId}"
									r.args = args
									r.count = 2
									return r, true
								case "GET":
									r.name = GetCategoryOperation
									r.summary = "カテゴリ詳細取得"
									r.operationID = "getCategory"
									r.pathPattern = "/workspaces/{wsId}/categories/{categoryId}"
									r.args = args
									r.count = 2
									return r, true
								case "PUT":
									r.name = UpdateCategoryOperation
									r.summary = "カテゴリ更新"
									r.operationID = "updateCategory"
									r.pathPattern = "/workspaces/{wsId}/categories/{categoryId}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'm': // Prefix: "members"

						if l := len("members"); len(elem) >= l && elem[0:l] == "members" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListMembersOperation
								r.summary = "メンバー一覧取得"
								r.operationID = "listMembers"
								r.pathPattern = "/workspaces/{wsId}/members"
								r.args = args
								r.count = 1
								return r, true
							case "POST":
								r.name = CreateMemberOperation
								r.summary = "メンバー追加"
								r.operationID = "createMember"
								r.pathPattern = "/workspaces/{wsId}/members"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "memberId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = DeleteMemberOperation
									r.summary = "メンバー削除"
									r.operationID = "deleteMember"
									r.pathPattern = "/workspaces/{wsId}/members/{memberId}"
									r.args = args
									r.count = 2
									return r, true
								case "GET":
									r.name = GetMemberOperation
									r.summary = "メンバー詳細取得"
									r.operationID = "getMember"
									r.pathPattern = "/workspaces/{wsId}/members/{memberId}"
									r.args = args
									r.count = 2
									return r, true
								case "PUT":
									r.name = UpdateMemberOperation
									r.summary = "メンバー更新"
									r.operationID = "updateMember"
									r.pathPattern = "/workspaces/{wsId}/members/{memberId}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 'r': // Prefix: "reports/"

						if l := len("reports/"); len(elem) >= l && elem[0:l] == "reports/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "account-balances"

							if l := len("account-balances"); len(elem) >= l && elem[0:l] == "account-balances" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetAccountBalancesOperation
									r.summary = "口座別残高サマリ取得"
									r.operationID = "getAccountBalances"
									r.pathPattern = "/workspaces/{wsId}/reports/account-balances"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'c': // Prefix: "category-expenses"

							if l := len("category-expenses"); len(elem) >= l && elem[0:l] == "category-expenses" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetCategoryExpensesOperation
									r.summary = "カテゴリ別支出集計取得"
									r.operationID = "getCategoryExpenses"
									r.pathPattern = "/workspaces/{wsId}/reports/category-expenses"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'd': // Prefix: "dashboard"

							if l := len("dashboard"); len(elem) >= l && elem[0:l] == "dashboard" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetDashboardOperation
									r.summary = "ダッシュボード概要取得"
									r.operationID = "getDashboard"
									r.pathPattern = "/workspaces/{wsId}/reports/dashboard"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					case 't': // Prefix: "transactions"

						if l := len("transactions"); len(elem) >= l && elem[0:l] == "transactions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListTransactionsOperation
								r.summary = "取引一覧取得（フィルタ可能）"
								r.operationID = "listTransactions"
								r.pathPattern = "/workspaces/{wsId}/transactions"
								r.args = args
								r.count = 1
								return r, true
							case "POST":
								r.name = CreateTransactionOperation
								r.summary = "取引作成"
								r.operationID = "createTransaction"
								r.pathPattern = "/workspaces/{wsId}/transactions"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "txId"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = DeleteTransactionOperation
									r.summary = "取引削除"
									r.operationID = "deleteTransaction"
									r.pathPattern = "/workspaces/{wsId}/transactions/{txId}"
									r.args = args
									r.count = 2
									return r, true
								case "GET":
									r.name = GetTransactionOperation
									r.summary = "取引詳細取得"
									r.operationID = "getTransaction"
									r.pathPattern = "/workspaces/{wsId}/transactions/{txId}"
									r.args = args
									r.count = 2
									return r, true
								case "PUT":
									r.name = UpdateTransactionOperation
									r.summary = "取引更新"
									r.operationID = "updateTransaction"
									r.pathPattern = "/workspaces/{wsId}/transactions/{txId}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			}

		}
	}
	return r, false
}
