// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	_ "embed"
	"io"
	"iter"
	"time"

	"github.com/google/uuid"
	enums "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen/dbenums"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed reports.bob.sql
var formattedQueries_reports string

var getCategoryExpenseSummarySQL = formattedQueries_reports[163:548]

type GetCategoryExpenseSummaryQuery = orm.ModQuery[*dialect.SelectQuery, getCategoryExpenseSummary, GetCategoryExpenseSummaryRow, []GetCategoryExpenseSummaryRow, getCategoryExpenseSummaryTransformer]

func GetCategoryExpenseSummary(OccurredAt time.Time, OccurredAt2 time.Time, WorkspaceID uuid.UUID) *GetCategoryExpenseSummaryQuery {
	var expressionTypArgs getCategoryExpenseSummary

	expressionTypArgs.OccurredAt = psql.Arg(OccurredAt)
	expressionTypArgs.OccurredAt2 = psql.Arg(OccurredAt2)
	expressionTypArgs.WorkspaceID = psql.Arg(WorkspaceID)

	return &GetCategoryExpenseSummaryQuery{
		Query: orm.Query[getCategoryExpenseSummary, GetCategoryExpenseSummaryRow, []GetCategoryExpenseSummaryRow, getCategoryExpenseSummaryTransformer]{
			ExecQuery: orm.ExecQuery[getCategoryExpenseSummary]{
				BaseQuery: bob.BaseQuery[getCategoryExpenseSummary]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (GetCategoryExpenseSummaryRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t GetCategoryExpenseSummaryRow
						row.ScheduleScanByIndex(0, &t.CategoryID)
						row.ScheduleScanByIndex(1, &t.CategoryName)
						row.ScheduleScanByIndex(2, &t.TotalExpense)
						return &t, nil
					}, func(v any) (GetCategoryExpenseSummaryRow, error) {
						return *(v.(*GetCategoryExpenseSummaryRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(9, 102))
			q.SetTable(expressionTypArgs.subExpr(108, 297))
			q.AppendWhere(expressionTypArgs.subExpr(304, 323))
			q.AppendGroup(expressionTypArgs.subExpr(333, 345))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(355, 385))
		}),
	}
}

type GetCategoryExpenseSummaryRow = struct {
	CategoryID   uuid.UUID       `db:"category_id"`
	CategoryName string          `db:"category_name"`
	TotalExpense decimal.Decimal `db:"total_expense"`
}

type getCategoryExpenseSummaryTransformer = bob.SliceTransformer[GetCategoryExpenseSummaryRow, []GetCategoryExpenseSummaryRow]

type getCategoryExpenseSummary struct {
	OccurredAt  bob.Expression
	OccurredAt2 bob.Expression
	WorkspaceID bob.Expression
}

func (o getCategoryExpenseSummary) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "occurredAt",
			Start:      270,
			Stop:       272,
			Expression: o.OccurredAt,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "occurredAt2",
			Start:      295,
			Stop:       297,
			Expression: o.OccurredAt2,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "workspaceID",
			Start:      321,
			Stop:       323,
			Expression: o.WorkspaceID,
		}) {
			return
		}
	}
}

func (o getCategoryExpenseSummary) raw(from, to int) string {
	return getCategoryExpenseSummarySQL[from:to]
}

func (o getCategoryExpenseSummary) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(getCategoryExpenseSummarySQL, from, to, o.args())
}

func (o getCategoryExpenseSummary) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(getCategoryExpenseSummarySQL)).WriteSQL(ctx, w, d, start)
}

var getAccountBalanceSummarySQL = formattedQueries_reports[579:1346]

type GetAccountBalanceSummaryQuery = orm.ModQuery[*dialect.SelectQuery, getAccountBalanceSummary, GetAccountBalanceSummaryRow, []GetAccountBalanceSummaryRow, getAccountBalanceSummaryTransformer]

func GetAccountBalanceSummary(OccurredAt time.Time, WorkspaceID uuid.UUID) *GetAccountBalanceSummaryQuery {
	var expressionTypArgs getAccountBalanceSummary

	expressionTypArgs.OccurredAt = psql.Arg(OccurredAt)
	expressionTypArgs.WorkspaceID = psql.Arg(WorkspaceID)

	return &GetAccountBalanceSummaryQuery{
		Query: orm.Query[getAccountBalanceSummary, GetAccountBalanceSummaryRow, []GetAccountBalanceSummaryRow, getAccountBalanceSummaryTransformer]{
			ExecQuery: orm.ExecQuery[getAccountBalanceSummary]{
				BaseQuery: bob.BaseQuery[getAccountBalanceSummary]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (GetAccountBalanceSummaryRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t GetAccountBalanceSummaryRow
						row.ScheduleScanByIndex(0, &t.AccountID)
						row.ScheduleScanByIndex(1, &t.AccountName)
						row.ScheduleScanByIndex(2, &t.AccountType)
						row.ScheduleScanByIndex(3, &t.CurrentBalance)
						return &t, nil
					}, func(v any) (GetAccountBalanceSummaryRow, error) {
						return *(v.(*GetAccountBalanceSummaryRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(9, 497))
			q.SetTable(expressionTypArgs.subExpr(503, 664))
			q.AppendWhere(expressionTypArgs.subExpr(671, 690))
			q.AppendGroup(expressionTypArgs.subExpr(700, 747))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(757, 767))
		}),
	}
}

type GetAccountBalanceSummaryRow = struct {
	AccountID      uuid.UUID         `db:"account_id"`
	AccountName    string            `db:"account_name"`
	AccountType    enums.AccountType `db:"account_type"`
	CurrentBalance decimal.Decimal   `db:"current_balance"`
}

type getAccountBalanceSummaryTransformer = bob.SliceTransformer[GetAccountBalanceSummaryRow, []GetAccountBalanceSummaryRow]

type getAccountBalanceSummary struct {
	OccurredAt  bob.Expression
	WorkspaceID bob.Expression
}

func (o getAccountBalanceSummary) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "occurredAt",
			Start:      662,
			Stop:       664,
			Expression: o.OccurredAt,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "workspaceID",
			Start:      688,
			Stop:       690,
			Expression: o.WorkspaceID,
		}) {
			return
		}
	}
}

func (o getAccountBalanceSummary) raw(from, to int) string {
	return getAccountBalanceSummarySQL[from:to]
}

func (o getAccountBalanceSummary) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(getAccountBalanceSummarySQL, from, to, o.args())
}

func (o getAccountBalanceSummary) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(getAccountBalanceSummarySQL)).WriteSQL(ctx, w, d, start)
}

var getWorkspaceDashboardSQL = formattedQueries_reports[1374:1857]

type GetWorkspaceDashboardQuery = orm.ModQuery[*dialect.SelectQuery, getWorkspaceDashboard, GetWorkspaceDashboardRow, []GetWorkspaceDashboardRow, getWorkspaceDashboardTransformer]

func GetWorkspaceDashboard(WorkspaceID uuid.UUID, OccurredAt time.Time, OccurredAt2 time.Time) *GetWorkspaceDashboardQuery {
	var expressionTypArgs getWorkspaceDashboard

	expressionTypArgs.WorkspaceID = psql.Arg(WorkspaceID)
	expressionTypArgs.OccurredAt = psql.Arg(OccurredAt)
	expressionTypArgs.OccurredAt2 = psql.Arg(OccurredAt2)

	return &GetWorkspaceDashboardQuery{
		Query: orm.Query[getWorkspaceDashboard, GetWorkspaceDashboardRow, []GetWorkspaceDashboardRow, getWorkspaceDashboardTransformer]{
			ExecQuery: orm.ExecQuery[getWorkspaceDashboard]{
				BaseQuery: bob.BaseQuery[getWorkspaceDashboard]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (GetWorkspaceDashboardRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t GetWorkspaceDashboardRow
						row.ScheduleScanByIndex(0, &t.WorkspaceID)
						row.ScheduleScanByIndex(1, &t.TotalIncome)
						row.ScheduleScanByIndex(2, &t.TotalExpense)
						row.ScheduleScanByIndex(3, &t.NetFlow)
						row.ScheduleScanByIndex(4, &t.TransactionCount)
						return &t, nil
					}, func(v any) (GetWorkspaceDashboardRow, error) {
						return *(v.(*GetWorkspaceDashboardRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(9, 386))
			q.SetTable(expressionTypArgs.subExpr(392, 406))
			q.AppendWhere(expressionTypArgs.subExpr(413, 483))
		}),
	}
}

type GetWorkspaceDashboardRow = struct {
	WorkspaceID      uuid.UUID       `db:"workspace_id"`
	TotalIncome      decimal.Decimal `db:"total_income"`
	TotalExpense     decimal.Decimal `db:"total_expense"`
	NetFlow          decimal.Decimal `db:"net_flow"`
	TransactionCount int64           `db:"transaction_count"`
}

type getWorkspaceDashboardTransformer = bob.SliceTransformer[GetWorkspaceDashboardRow, []GetWorkspaceDashboardRow]

type getWorkspaceDashboard struct {
	WorkspaceID bob.Expression
	OccurredAt  bob.Expression
	OccurredAt2 bob.Expression
}

func (o getWorkspaceDashboard) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "workspaceID",
			Start:      9,
			Stop:       11,
			Expression: o.WorkspaceID,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "workspaceID",
			Start:      430,
			Stop:       432,
			Expression: o.WorkspaceID,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "occurredAt",
			Start:      456,
			Stop:       458,
			Expression: o.OccurredAt,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "occurredAt2",
			Start:      481,
			Stop:       483,
			Expression: o.OccurredAt2,
		}) {
			return
		}
	}
}

func (o getWorkspaceDashboard) raw(from, to int) string {
	return getWorkspaceDashboardSQL[from:to]
}

func (o getWorkspaceDashboard) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(getWorkspaceDashboardSQL, from, to, o.args())
}

func (o getWorkspaceDashboard) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(getWorkspaceDashboardSQL)).WriteSQL(ctx, w, d, start)
}
