/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Kakeibo API
 * マルチテナント家計簿システム API
 * OpenAPI spec version: 1.0.0
 */
import type { AccountType } from "./accountType";

export interface Account {
  id: string;
  workspaceId: string;
  /** @maxLength 100 */
  name: string;
  accountType: AccountType;
  /** Decimal amount (e.g. "1000.00") */
  initialBalance: string;
}
