/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Kakeibo API
 * マルチテナント家計簿システム API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateWorkspaceRequest {
  /** @maxLength 100 */
  name: string;
}
