// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	enums "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen/dbenums"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Account is an object representing the database table.
type Account struct {
	ID             uuid.UUID         `db:"id,pk" json:"id"`
	WorkspaceID    uuid.UUID         `db:"workspace_id" json:"workspace_id"`
	Name           string            `db:"name" json:"name"`
	AccountType    enums.AccountType `db:"account_type" json:"account_type"`
	InitialBalance decimal.Decimal   `db:"initial_balance" json:"initial_balance"`

	R accountR `db:"-" json:"-"`
}

// AccountSlice is an alias for a slice of pointers to Account.
// This should almost always be used instead of []*Account.
type AccountSlice []*Account

// Accounts contains methods to work with the accounts table
var Accounts = psql.NewTablex[*Account, AccountSlice, *AccountSetter]("", "accounts", buildAccountColumns("accounts"))

// AccountsQuery is a query on the accounts table
type AccountsQuery = *psql.ViewQuery[*Account, AccountSlice]

// accountR is where relationships are stored.
type accountR struct {
	Workspace                *Workspace       `json:"Workspace"`                // accounts.fk_accounts_workspace
	Transactions             TransactionSlice `json:"Transactions"`             // transactions.fk_transactions_account
	CounterpartyTransactions TransactionSlice `json:"CounterpartyTransactions"` // transactions.fk_transactions_counterparty_account
}

func buildAccountColumns(alias string) accountColumns {
	return accountColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "workspace_id", "name", "account_type", "initial_balance",
		).WithParent("accounts"),
		tableAlias:     alias,
		ID:             psql.Quote(alias, "id"),
		WorkspaceID:    psql.Quote(alias, "workspace_id"),
		Name:           psql.Quote(alias, "name"),
		AccountType:    psql.Quote(alias, "account_type"),
		InitialBalance: psql.Quote(alias, "initial_balance"),
	}
}

type accountColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             psql.Expression
	WorkspaceID    psql.Expression
	Name           psql.Expression
	AccountType    psql.Expression
	InitialBalance psql.Expression
}

func (c accountColumns) Alias() string {
	return c.tableAlias
}

func (accountColumns) AliasedAs(alias string) accountColumns {
	return buildAccountColumns(alias)
}

// AccountSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AccountSetter struct {
	ID             omit.Val[uuid.UUID]         `db:"id,pk" json:"id"`
	WorkspaceID    omit.Val[uuid.UUID]         `db:"workspace_id" json:"workspace_id"`
	Name           omit.Val[string]            `db:"name" json:"name"`
	AccountType    omit.Val[enums.AccountType] `db:"account_type" json:"account_type"`
	InitialBalance omit.Val[decimal.Decimal]   `db:"initial_balance" json:"initial_balance"`
}

func (s AccountSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.WorkspaceID.IsValue() {
		vals = append(vals, "workspace_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.AccountType.IsValue() {
		vals = append(vals, "account_type")
	}
	if s.InitialBalance.IsValue() {
		vals = append(vals, "initial_balance")
	}
	return vals
}

func (s AccountSetter) Overwrite(t *Account) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.WorkspaceID.IsValue() {
		t.WorkspaceID = s.WorkspaceID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.AccountType.IsValue() {
		t.AccountType = s.AccountType.MustGet()
	}
	if s.InitialBalance.IsValue() {
		t.InitialBalance = s.InitialBalance.MustGet()
	}
}

func (s *AccountSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Accounts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.WorkspaceID.IsValue() {
			vals[1] = psql.Arg(s.WorkspaceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.AccountType.IsValue() {
			vals[3] = psql.Arg(s.AccountType.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.InitialBalance.IsValue() {
			vals[4] = psql.Arg(s.InitialBalance.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AccountSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AccountSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.WorkspaceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "workspace_id")...),
			psql.Arg(s.WorkspaceID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.AccountType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_type")...),
			psql.Arg(s.AccountType),
		}})
	}

	if s.InitialBalance.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "initial_balance")...),
			psql.Arg(s.InitialBalance),
		}})
	}

	return exprs
}

// FindAccount retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAccount(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Account, error) {
	if len(cols) == 0 {
		return Accounts.Query(
			sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Accounts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AccountExists checks the presence of a single record by primary key
func AccountExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Account is retrieved from the database
func (o *Account) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, AccountSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Account
func (o *Account) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Account) pkEQ() dialect.Expression {
	return psql.Quote("accounts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Account
func (o *Account) Update(ctx context.Context, exec bob.Executor, s *AccountSetter) error {
	v, err := Accounts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Account record with an executor
func (o *Account) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Accounts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Account using the executor
func (o *Account) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AccountSlice is retrieved from the database
func (o AccountSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AccountSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("accounts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AccountSlice) copyMatchingRows(from ...*Account) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AccountSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterUpdateHooks on the slice
				_, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AccountSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterDeleteHooks on the slice
				_, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AccountSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AccountSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AccountSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AccountSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Accounts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Workspace starts a query for related objects on workspaces
func (o *Account) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	return Workspaces.Query(append(mods,
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.WorkspaceID))),
	)...)
}

func (os AccountSlice) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
	))

	return Workspaces.Query(append(mods,
		sm.Where(psql.Group(Workspaces.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Transactions starts a query for related objects on transactions
func (o *Account) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Transactions.Columns.AccountID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Transactions.Query(append(mods,
		sm.Where(psql.Group(Transactions.Columns.WorkspaceID, Transactions.Columns.AccountID).OP("IN", PKArgExpr)),
	)...)
}

// CounterpartyTransactions starts a query for related objects on transactions
func (o *Account) CounterpartyTransactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Transactions.Columns.CounterpartyAccountID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) CounterpartyTransactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Transactions.Query(append(mods,
		sm.Where(psql.Group(Transactions.Columns.WorkspaceID, Transactions.Columns.CounterpartyAccountID).OP("IN", PKArgExpr)),
	)...)
}

func attachAccountWorkspace0(ctx context.Context, exec bob.Executor, count int, account0 *Account, workspace1 *Workspace) (*Account, error) {
	setter := &AccountSetter{
		WorkspaceID: omit.From(workspace1.ID),
	}

	err := account0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountWorkspace0: %w", err)
	}

	return account0, nil
}

func (account0 *Account) InsertWorkspace(ctx context.Context, exec bob.Executor, related *WorkspaceSetter) error {
	var err error

	workspace1, err := Workspaces.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAccountWorkspace0(ctx, exec, 1, account0, workspace1)
	if err != nil {
		return err
	}

	account0.R.Workspace = workspace1

	workspace1.R.Accounts = append(workspace1.R.Accounts, account0)

	return nil
}

func (account0 *Account) AttachWorkspace(ctx context.Context, exec bob.Executor, workspace1 *Workspace) error {
	var err error

	_, err = attachAccountWorkspace0(ctx, exec, 1, account0, workspace1)
	if err != nil {
		return err
	}

	account0.R.Workspace = workspace1

	workspace1.R.Accounts = append(workspace1.R.Accounts, account0)

	return nil
}

func insertAccountTransactions0(ctx context.Context, exec bob.Executor, transactions1 []*TransactionSetter, account0 *Account) (TransactionSlice, error) {
	for i := range transactions1 {
		transactions1[i].WorkspaceID = omit.From(account0.WorkspaceID)
		transactions1[i].AccountID = omitnull.From(account0.ID)
	}

	ret, err := Transactions.Insert(bob.ToMods(transactions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountTransactions0: %w", err)
	}

	return ret, nil
}

func attachAccountTransactions0(ctx context.Context, exec bob.Executor, count int, transactions1 TransactionSlice, account0 *Account) (TransactionSlice, error) {
	setter := &TransactionSetter{
		WorkspaceID: omit.From(account0.WorkspaceID),
		AccountID:   omitnull.From(account0.ID),
	}

	err := transactions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountTransactions0: %w", err)
	}

	return transactions1, nil
}

func (account0 *Account) InsertTransactions(ctx context.Context, exec bob.Executor, related ...*TransactionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	transactions1, err := insertAccountTransactions0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.Transactions = append(account0.R.Transactions, transactions1...)

	for _, rel := range transactions1 {
		rel.R.Account = account0
	}
	return nil
}

func (account0 *Account) AttachTransactions(ctx context.Context, exec bob.Executor, related ...*Transaction) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	transactions1 := TransactionSlice(related)

	_, err = attachAccountTransactions0(ctx, exec, len(related), transactions1, account0)
	if err != nil {
		return err
	}

	account0.R.Transactions = append(account0.R.Transactions, transactions1...)

	for _, rel := range related {
		rel.R.Account = account0
	}

	return nil
}

func insertAccountCounterpartyTransactions0(ctx context.Context, exec bob.Executor, transactions1 []*TransactionSetter, account0 *Account) (TransactionSlice, error) {
	for i := range transactions1 {
		transactions1[i].WorkspaceID = omit.From(account0.WorkspaceID)
		transactions1[i].CounterpartyAccountID = omitnull.From(account0.ID)
	}

	ret, err := Transactions.Insert(bob.ToMods(transactions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountCounterpartyTransactions0: %w", err)
	}

	return ret, nil
}

func attachAccountCounterpartyTransactions0(ctx context.Context, exec bob.Executor, count int, transactions1 TransactionSlice, account0 *Account) (TransactionSlice, error) {
	setter := &TransactionSetter{
		WorkspaceID:           omit.From(account0.WorkspaceID),
		CounterpartyAccountID: omitnull.From(account0.ID),
	}

	err := transactions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountCounterpartyTransactions0: %w", err)
	}

	return transactions1, nil
}

func (account0 *Account) InsertCounterpartyTransactions(ctx context.Context, exec bob.Executor, related ...*TransactionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	transactions1, err := insertAccountCounterpartyTransactions0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.CounterpartyTransactions = append(account0.R.CounterpartyTransactions, transactions1...)

	for _, rel := range transactions1 {
		rel.R.CounterpartyAccount = account0
	}
	return nil
}

func (account0 *Account) AttachCounterpartyTransactions(ctx context.Context, exec bob.Executor, related ...*Transaction) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	transactions1 := TransactionSlice(related)

	_, err = attachAccountCounterpartyTransactions0(ctx, exec, len(related), transactions1, account0)
	if err != nil {
		return err
	}

	account0.R.CounterpartyTransactions = append(account0.R.CounterpartyTransactions, transactions1...)

	for _, rel := range related {
		rel.R.CounterpartyAccount = account0
	}

	return nil
}

type accountWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, uuid.UUID]
	WorkspaceID    psql.WhereMod[Q, uuid.UUID]
	Name           psql.WhereMod[Q, string]
	AccountType    psql.WhereMod[Q, enums.AccountType]
	InitialBalance psql.WhereMod[Q, decimal.Decimal]
}

func (accountWhere[Q]) AliasedAs(alias string) accountWhere[Q] {
	return buildAccountWhere[Q](buildAccountColumns(alias))
}

func buildAccountWhere[Q psql.Filterable](cols accountColumns) accountWhere[Q] {
	return accountWhere[Q]{
		ID:             psql.Where[Q, uuid.UUID](cols.ID),
		WorkspaceID:    psql.Where[Q, uuid.UUID](cols.WorkspaceID),
		Name:           psql.Where[Q, string](cols.Name),
		AccountType:    psql.Where[Q, enums.AccountType](cols.AccountType),
		InitialBalance: psql.Where[Q, decimal.Decimal](cols.InitialBalance),
	}
}

func (o *Account) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Workspace":
		rel, ok := retrieved.(*Workspace)
		if !ok {
			return fmt.Errorf("account cannot load %T as %q", retrieved, name)
		}

		o.R.Workspace = rel

		if rel != nil {
			rel.R.Accounts = AccountSlice{o}
		}
		return nil
	case "Transactions":
		rels, ok := retrieved.(TransactionSlice)
		if !ok {
			return fmt.Errorf("account cannot load %T as %q", retrieved, name)
		}

		o.R.Transactions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Account = o
			}
		}
		return nil
	case "CounterpartyTransactions":
		rels, ok := retrieved.(TransactionSlice)
		if !ok {
			return fmt.Errorf("account cannot load %T as %q", retrieved, name)
		}

		o.R.CounterpartyTransactions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.CounterpartyAccount = o
			}
		}
		return nil
	default:
		return fmt.Errorf("account has no relationship %q", name)
	}
}

type accountPreloader struct {
	Workspace func(...psql.PreloadOption) psql.Preloader
}

func buildAccountPreloader() accountPreloader {
	return accountPreloader{
		Workspace: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Workspace, WorkspaceSlice](psql.PreloadRel{
				Name: "Workspace",
				Sides: []psql.PreloadSide{
					{
						From:        Accounts,
						To:          Workspaces,
						FromColumns: []string{"workspace_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Workspaces.Columns.Names(), opts...)
		},
	}
}

type accountThenLoader[Q orm.Loadable] struct {
	Workspace                func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transactions             func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CounterpartyTransactions func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAccountThenLoader[Q orm.Loadable]() accountThenLoader[Q] {
	type WorkspaceLoadInterface interface {
		LoadWorkspace(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TransactionsLoadInterface interface {
		LoadTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CounterpartyTransactionsLoadInterface interface {
		LoadCounterpartyTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return accountThenLoader[Q]{
		Workspace: thenLoadBuilder[Q](
			"Workspace",
			func(ctx context.Context, exec bob.Executor, retrieved WorkspaceLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadWorkspace(ctx, exec, mods...)
			},
		),
		Transactions: thenLoadBuilder[Q](
			"Transactions",
			func(ctx context.Context, exec bob.Executor, retrieved TransactionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTransactions(ctx, exec, mods...)
			},
		),
		CounterpartyTransactions: thenLoadBuilder[Q](
			"CounterpartyTransactions",
			func(ctx context.Context, exec bob.Executor, retrieved CounterpartyTransactionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCounterpartyTransactions(ctx, exec, mods...)
			},
		),
	}
}

// LoadWorkspace loads the account's Workspace into the .R struct
func (o *Account) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Workspace = nil

	related, err := o.Workspace(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Accounts = AccountSlice{o}

	o.R.Workspace = related
	return nil
}

// LoadWorkspace loads the account's Workspace into the .R struct
func (os AccountSlice) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	workspaces, err := os.Workspace(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range workspaces {

			if !(o.WorkspaceID == rel.ID) {
				continue
			}

			rel.R.Accounts = append(rel.R.Accounts, o)

			o.R.Workspace = rel
			break
		}
	}

	return nil
}

// LoadTransactions loads the account's Transactions into the .R struct
func (o *Account) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transactions = nil

	related, err := o.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Account = o
	}

	o.R.Transactions = related
	return nil
}

// LoadTransactions loads the account's Transactions into the .R struct
func (os AccountSlice) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transactions, err := os.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Transactions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range transactions {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !rel.AccountID.IsValue() {
				continue
			}
			if !(rel.AccountID.IsValue() && o.ID == rel.AccountID.MustGet()) {
				continue
			}

			rel.R.Account = o

			o.R.Transactions = append(o.R.Transactions, rel)
		}
	}

	return nil
}

// LoadCounterpartyTransactions loads the account's CounterpartyTransactions into the .R struct
func (o *Account) LoadCounterpartyTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CounterpartyTransactions = nil

	related, err := o.CounterpartyTransactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.CounterpartyAccount = o
	}

	o.R.CounterpartyTransactions = related
	return nil
}

// LoadCounterpartyTransactions loads the account's CounterpartyTransactions into the .R struct
func (os AccountSlice) LoadCounterpartyTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transactions, err := os.CounterpartyTransactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CounterpartyTransactions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range transactions {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !rel.CounterpartyAccountID.IsValue() {
				continue
			}
			if !(rel.CounterpartyAccountID.IsValue() && o.ID == rel.CounterpartyAccountID.MustGet()) {
				continue
			}

			rel.R.CounterpartyAccount = o

			o.R.CounterpartyTransactions = append(o.R.CounterpartyTransactions, rel)
		}
	}

	return nil
}

type accountJoins[Q dialect.Joinable] struct {
	typ                      string
	Workspace                modAs[Q, workspaceColumns]
	Transactions             modAs[Q, transactionColumns]
	CounterpartyTransactions modAs[Q, transactionColumns]
}

func (j accountJoins[Q]) aliasedAs(alias string) accountJoins[Q] {
	return buildAccountJoins[Q](buildAccountColumns(alias), j.typ)
}

func buildAccountJoins[Q dialect.Joinable](cols accountColumns, typ string) accountJoins[Q] {
	return accountJoins[Q]{
		typ: typ,
		Workspace: modAs[Q, workspaceColumns]{
			c: Workspaces.Columns,
			f: func(to workspaceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Workspaces.Name().As(to.Alias())).On(
						to.ID.EQ(cols.WorkspaceID),
					))
				}

				return mods
			},
		},
		Transactions: modAs[Q, transactionColumns]{
			c: Transactions.Columns,
			f: func(to transactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transactions.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.AccountID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		CounterpartyTransactions: modAs[Q, transactionColumns]{
			c: Transactions.Columns,
			f: func(to transactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transactions.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.CounterpartyAccountID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
