// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	enums "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen/dbenums"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Category is an object representing the database table.
type Category struct {
	ID           uuid.UUID           `db:"id,pk" json:"id"`
	WorkspaceID  uuid.UUID           `db:"workspace_id" json:"workspace_id"`
	Name         string              `db:"name" json:"name"`
	CategoryType enums.CategoryType  `db:"category_type" json:"category_type"`
	ParentID     null.Val[uuid.UUID] `db:"parent_id" json:"parent_id"`

	R categoryR `db:"-" json:"-"`
}

// CategorySlice is an alias for a slice of pointers to Category.
// This should almost always be used instead of []*Category.
type CategorySlice []*Category

// Categories contains methods to work with the categories table
var Categories = psql.NewTablex[*Category, CategorySlice, *CategorySetter]("", "categories", buildCategoryColumns("categories"))

// CategoriesQuery is a query on the categories table
type CategoriesQuery = *psql.ViewQuery[*Category, CategorySlice]

// categoryR is where relationships are stored.
type categoryR struct {
	Category          *Category        `json:"Category"`          // categories.fk_categories_parent
	ReverseCategories CategorySlice    `json:"ReverseCategories"` // categories.fk_categories_parent__self_join_reverse
	Workspace         *Workspace       `json:"Workspace"`         // categories.fk_categories_workspace
	Transactions      TransactionSlice `json:"Transactions"`      // transactions.fk_transactions_category
}

func buildCategoryColumns(alias string) categoryColumns {
	return categoryColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "workspace_id", "name", "category_type", "parent_id",
		).WithParent("categories"),
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		WorkspaceID:  psql.Quote(alias, "workspace_id"),
		Name:         psql.Quote(alias, "name"),
		CategoryType: psql.Quote(alias, "category_type"),
		ParentID:     psql.Quote(alias, "parent_id"),
	}
}

type categoryColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	ID           psql.Expression
	WorkspaceID  psql.Expression
	Name         psql.Expression
	CategoryType psql.Expression
	ParentID     psql.Expression
}

func (c categoryColumns) Alias() string {
	return c.tableAlias
}

func (categoryColumns) AliasedAs(alias string) categoryColumns {
	return buildCategoryColumns(alias)
}

// CategorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CategorySetter struct {
	ID           omit.Val[uuid.UUID]          `db:"id,pk" json:"id"`
	WorkspaceID  omit.Val[uuid.UUID]          `db:"workspace_id" json:"workspace_id"`
	Name         omit.Val[string]             `db:"name" json:"name"`
	CategoryType omit.Val[enums.CategoryType] `db:"category_type" json:"category_type"`
	ParentID     omitnull.Val[uuid.UUID]      `db:"parent_id" json:"parent_id"`
}

func (s CategorySetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.WorkspaceID.IsValue() {
		vals = append(vals, "workspace_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.CategoryType.IsValue() {
		vals = append(vals, "category_type")
	}
	if !s.ParentID.IsUnset() {
		vals = append(vals, "parent_id")
	}
	return vals
}

func (s CategorySetter) Overwrite(t *Category) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.WorkspaceID.IsValue() {
		t.WorkspaceID = s.WorkspaceID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.CategoryType.IsValue() {
		t.CategoryType = s.CategoryType.MustGet()
	}
	if !s.ParentID.IsUnset() {
		t.ParentID = s.ParentID.MustGetNull()
	}
}

func (s *CategorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Categories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.WorkspaceID.IsValue() {
			vals[1] = psql.Arg(s.WorkspaceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CategoryType.IsValue() {
			vals[3] = psql.Arg(s.CategoryType.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.ParentID.IsUnset() {
			vals[4] = psql.Arg(s.ParentID.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CategorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CategorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.WorkspaceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "workspace_id")...),
			psql.Arg(s.WorkspaceID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CategoryType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category_type")...),
			psql.Arg(s.CategoryType),
		}})
	}

	if !s.ParentID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "parent_id")...),
			psql.Arg(s.ParentID),
		}})
	}

	return exprs
}

// FindCategory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCategory(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Category, error) {
	if len(cols) == 0 {
		return Categories.Query(
			sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Categories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CategoryExists checks the presence of a single record by primary key
func CategoryExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Category is retrieved from the database
func (o *Category) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, CategorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Category
func (o *Category) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Category) pkEQ() dialect.Expression {
	return psql.Quote("categories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Category
func (o *Category) Update(ctx context.Context, exec bob.Executor, s *CategorySetter) error {
	v, err := Categories.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Category record with an executor
func (o *Category) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Categories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Category using the executor
func (o *Category) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CategorySlice is retrieved from the database
func (o CategorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CategorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("categories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CategorySlice) copyMatchingRows(from ...*Category) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CategorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterUpdateHooks on the slice
				_, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CategorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterDeleteHooks on the slice
				_, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CategorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CategorySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CategorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CategorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Categories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Category starts a query for related objects on categories
func (o *Category) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.ParentID))),
	)...)
}

func (os CategorySlice) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkParentID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkParentID = append(pkParentID, o.ParentID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkParentID), "uuid[]")),
	))

	return Categories.Query(append(mods,
		sm.Where(psql.Group(Categories.Columns.WorkspaceID, Categories.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ReverseCategories starts a query for related objects on categories
func (o *Category) ReverseCategories(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Categories.Columns.ParentID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CategorySlice) ReverseCategories(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Categories.Query(append(mods,
		sm.Where(psql.Group(Categories.Columns.WorkspaceID, Categories.Columns.ParentID).OP("IN", PKArgExpr)),
	)...)
}

// Workspace starts a query for related objects on workspaces
func (o *Category) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	return Workspaces.Query(append(mods,
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.WorkspaceID))),
	)...)
}

func (os CategorySlice) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
	))

	return Workspaces.Query(append(mods,
		sm.Where(psql.Group(Workspaces.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Transactions starts a query for related objects on transactions
func (o *Category) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Transactions.Columns.CategoryID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CategorySlice) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Transactions.Query(append(mods,
		sm.Where(psql.Group(Transactions.Columns.WorkspaceID, Transactions.Columns.CategoryID).OP("IN", PKArgExpr)),
	)...)
}

func attachCategoryCategory0(ctx context.Context, exec bob.Executor, count int, category0 *Category, category1 *Category) (*Category, error) {
	setter := &CategorySetter{
		WorkspaceID: omit.From(category1.WorkspaceID),
		ParentID:    omitnull.From(category1.ID),
	}

	err := category0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryCategory0: %w", err)
	}

	return category0, nil
}

func (category0 *Category) InsertCategory(ctx context.Context, exec bob.Executor, related *CategorySetter) error {
	var err error

	category1, err := Categories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCategoryCategory0(ctx, exec, 1, category0, category1)
	if err != nil {
		return err
	}

	category0.R.Category = category1

	category1.R.Category = category0

	return nil
}

func (category0 *Category) AttachCategory(ctx context.Context, exec bob.Executor, category1 *Category) error {
	var err error

	_, err = attachCategoryCategory0(ctx, exec, 1, category0, category1)
	if err != nil {
		return err
	}

	category0.R.Category = category1

	category1.R.Category = category0

	return nil
}

func insertCategoryReverseCategories0(ctx context.Context, exec bob.Executor, categories1 []*CategorySetter, category0 *Category) (CategorySlice, error) {
	for i := range categories1 {
		categories1[i].WorkspaceID = omit.From(category0.WorkspaceID)
		categories1[i].ParentID = omitnull.From(category0.ID)
	}

	ret, err := Categories.Insert(bob.ToMods(categories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCategoryReverseCategories0: %w", err)
	}

	return ret, nil
}

func attachCategoryReverseCategories0(ctx context.Context, exec bob.Executor, count int, categories1 CategorySlice, category0 *Category) (CategorySlice, error) {
	setter := &CategorySetter{
		WorkspaceID: omit.From(category0.WorkspaceID),
		ParentID:    omitnull.From(category0.ID),
	}

	err := categories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryReverseCategories0: %w", err)
	}

	return categories1, nil
}

func (category0 *Category) InsertReverseCategories(ctx context.Context, exec bob.Executor, related ...*CategorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	categories1, err := insertCategoryReverseCategories0(ctx, exec, related, category0)
	if err != nil {
		return err
	}

	category0.R.ReverseCategories = append(category0.R.ReverseCategories, categories1...)

	for _, rel := range categories1 {
		rel.R.ReverseCategories = append(rel.R.ReverseCategories, category0)
	}
	return nil
}

func (category0 *Category) AttachReverseCategories(ctx context.Context, exec bob.Executor, related ...*Category) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	categories1 := CategorySlice(related)

	_, err = attachCategoryReverseCategories0(ctx, exec, len(related), categories1, category0)
	if err != nil {
		return err
	}

	category0.R.ReverseCategories = append(category0.R.ReverseCategories, categories1...)

	for _, rel := range related {
		rel.R.ReverseCategories = append(rel.R.ReverseCategories, category0)
	}

	return nil
}

func attachCategoryWorkspace0(ctx context.Context, exec bob.Executor, count int, category0 *Category, workspace1 *Workspace) (*Category, error) {
	setter := &CategorySetter{
		WorkspaceID: omit.From(workspace1.ID),
	}

	err := category0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryWorkspace0: %w", err)
	}

	return category0, nil
}

func (category0 *Category) InsertWorkspace(ctx context.Context, exec bob.Executor, related *WorkspaceSetter) error {
	var err error

	workspace1, err := Workspaces.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCategoryWorkspace0(ctx, exec, 1, category0, workspace1)
	if err != nil {
		return err
	}

	category0.R.Workspace = workspace1

	workspace1.R.Categories = append(workspace1.R.Categories, category0)

	return nil
}

func (category0 *Category) AttachWorkspace(ctx context.Context, exec bob.Executor, workspace1 *Workspace) error {
	var err error

	_, err = attachCategoryWorkspace0(ctx, exec, 1, category0, workspace1)
	if err != nil {
		return err
	}

	category0.R.Workspace = workspace1

	workspace1.R.Categories = append(workspace1.R.Categories, category0)

	return nil
}

func insertCategoryTransactions0(ctx context.Context, exec bob.Executor, transactions1 []*TransactionSetter, category0 *Category) (TransactionSlice, error) {
	for i := range transactions1 {
		transactions1[i].WorkspaceID = omit.From(category0.WorkspaceID)
		transactions1[i].CategoryID = omitnull.From(category0.ID)
	}

	ret, err := Transactions.Insert(bob.ToMods(transactions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCategoryTransactions0: %w", err)
	}

	return ret, nil
}

func attachCategoryTransactions0(ctx context.Context, exec bob.Executor, count int, transactions1 TransactionSlice, category0 *Category) (TransactionSlice, error) {
	setter := &TransactionSetter{
		WorkspaceID: omit.From(category0.WorkspaceID),
		CategoryID:  omitnull.From(category0.ID),
	}

	err := transactions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryTransactions0: %w", err)
	}

	return transactions1, nil
}

func (category0 *Category) InsertTransactions(ctx context.Context, exec bob.Executor, related ...*TransactionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	transactions1, err := insertCategoryTransactions0(ctx, exec, related, category0)
	if err != nil {
		return err
	}

	category0.R.Transactions = append(category0.R.Transactions, transactions1...)

	for _, rel := range transactions1 {
		rel.R.Category = category0
	}
	return nil
}

func (category0 *Category) AttachTransactions(ctx context.Context, exec bob.Executor, related ...*Transaction) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	transactions1 := TransactionSlice(related)

	_, err = attachCategoryTransactions0(ctx, exec, len(related), transactions1, category0)
	if err != nil {
		return err
	}

	category0.R.Transactions = append(category0.R.Transactions, transactions1...)

	for _, rel := range related {
		rel.R.Category = category0
	}

	return nil
}

type categoryWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, uuid.UUID]
	WorkspaceID  psql.WhereMod[Q, uuid.UUID]
	Name         psql.WhereMod[Q, string]
	CategoryType psql.WhereMod[Q, enums.CategoryType]
	ParentID     psql.WhereNullMod[Q, uuid.UUID]
}

func (categoryWhere[Q]) AliasedAs(alias string) categoryWhere[Q] {
	return buildCategoryWhere[Q](buildCategoryColumns(alias))
}

func buildCategoryWhere[Q psql.Filterable](cols categoryColumns) categoryWhere[Q] {
	return categoryWhere[Q]{
		ID:           psql.Where[Q, uuid.UUID](cols.ID),
		WorkspaceID:  psql.Where[Q, uuid.UUID](cols.WorkspaceID),
		Name:         psql.Where[Q, string](cols.Name),
		CategoryType: psql.Where[Q, enums.CategoryType](cols.CategoryType),
		ParentID:     psql.WhereNull[Q, uuid.UUID](cols.ParentID),
	}
}

func (o *Category) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Category":
		rel, ok := retrieved.(*Category)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Category = rel

		if rel != nil {
			rel.R.Category = o
		}
		return nil
	case "ReverseCategories":
		rels, ok := retrieved.(CategorySlice)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.ReverseCategories = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.ReverseCategories = CategorySlice{o}
			}
		}
		return nil
	case "Workspace":
		rel, ok := retrieved.(*Workspace)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Workspace = rel

		if rel != nil {
			rel.R.Categories = CategorySlice{o}
		}
		return nil
	case "Transactions":
		rels, ok := retrieved.(TransactionSlice)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Transactions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Category = o
			}
		}
		return nil
	default:
		return fmt.Errorf("category has no relationship %q", name)
	}
}

type categoryPreloader struct {
	Category  func(...psql.PreloadOption) psql.Preloader
	Workspace func(...psql.PreloadOption) psql.Preloader
}

func buildCategoryPreloader() categoryPreloader {
	return categoryPreloader{
		Category: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Category, CategorySlice](psql.PreloadRel{
				Name: "Category",
				Sides: []psql.PreloadSide{
					{
						From:        Categories,
						To:          Categories,
						FromColumns: []string{"workspace_id", "parent_id"},
						ToColumns:   []string{"workspace_id", "id"},
					},
				},
			}, Categories.Columns.Names(), opts...)
		},
		Workspace: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Workspace, WorkspaceSlice](psql.PreloadRel{
				Name: "Workspace",
				Sides: []psql.PreloadSide{
					{
						From:        Categories,
						To:          Workspaces,
						FromColumns: []string{"workspace_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Workspaces.Columns.Names(), opts...)
		},
	}
}

type categoryThenLoader[Q orm.Loadable] struct {
	Category          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ReverseCategories func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Workspace         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transactions      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCategoryThenLoader[Q orm.Loadable]() categoryThenLoader[Q] {
	type CategoryLoadInterface interface {
		LoadCategory(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ReverseCategoriesLoadInterface interface {
		LoadReverseCategories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type WorkspaceLoadInterface interface {
		LoadWorkspace(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TransactionsLoadInterface interface {
		LoadTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return categoryThenLoader[Q]{
		Category: thenLoadBuilder[Q](
			"Category",
			func(ctx context.Context, exec bob.Executor, retrieved CategoryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCategory(ctx, exec, mods...)
			},
		),
		ReverseCategories: thenLoadBuilder[Q](
			"ReverseCategories",
			func(ctx context.Context, exec bob.Executor, retrieved ReverseCategoriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadReverseCategories(ctx, exec, mods...)
			},
		),
		Workspace: thenLoadBuilder[Q](
			"Workspace",
			func(ctx context.Context, exec bob.Executor, retrieved WorkspaceLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadWorkspace(ctx, exec, mods...)
			},
		),
		Transactions: thenLoadBuilder[Q](
			"Transactions",
			func(ctx context.Context, exec bob.Executor, retrieved TransactionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTransactions(ctx, exec, mods...)
			},
		),
	}
}

// LoadCategory loads the category's Category into the .R struct
func (o *Category) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Category = nil

	related, err := o.Category(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Category = o

	o.R.Category = related
	return nil
}

// LoadCategory loads the category's Category into the .R struct
func (os CategorySlice) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Category(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range categories {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}
			if !o.ParentID.IsValue() {
				continue
			}

			if !(o.ParentID.IsValue() && o.ParentID.MustGet() == rel.ID) {
				continue
			}

			rel.R.Category = o

			o.R.Category = rel
			break
		}
	}

	return nil
}

// LoadReverseCategories loads the category's ReverseCategories into the .R struct
func (o *Category) LoadReverseCategories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ReverseCategories = nil

	related, err := o.ReverseCategories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ReverseCategories = CategorySlice{o}
	}

	o.R.ReverseCategories = related
	return nil
}

// LoadReverseCategories loads the category's ReverseCategories into the .R struct
func (os CategorySlice) LoadReverseCategories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.ReverseCategories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ReverseCategories = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range categories {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !rel.ParentID.IsValue() {
				continue
			}
			if !(rel.ParentID.IsValue() && o.ID == rel.ParentID.MustGet()) {
				continue
			}

			rel.R.ReverseCategories = append(rel.R.ReverseCategories, o)

			o.R.ReverseCategories = append(o.R.ReverseCategories, rel)
		}
	}

	return nil
}

// LoadWorkspace loads the category's Workspace into the .R struct
func (o *Category) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Workspace = nil

	related, err := o.Workspace(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Categories = CategorySlice{o}

	o.R.Workspace = related
	return nil
}

// LoadWorkspace loads the category's Workspace into the .R struct
func (os CategorySlice) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	workspaces, err := os.Workspace(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range workspaces {

			if !(o.WorkspaceID == rel.ID) {
				continue
			}

			rel.R.Categories = append(rel.R.Categories, o)

			o.R.Workspace = rel
			break
		}
	}

	return nil
}

// LoadTransactions loads the category's Transactions into the .R struct
func (o *Category) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transactions = nil

	related, err := o.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Category = o
	}

	o.R.Transactions = related
	return nil
}

// LoadTransactions loads the category's Transactions into the .R struct
func (os CategorySlice) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transactions, err := os.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Transactions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range transactions {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !rel.CategoryID.IsValue() {
				continue
			}
			if !(rel.CategoryID.IsValue() && o.ID == rel.CategoryID.MustGet()) {
				continue
			}

			rel.R.Category = o

			o.R.Transactions = append(o.R.Transactions, rel)
		}
	}

	return nil
}

type categoryJoins[Q dialect.Joinable] struct {
	typ               string
	Category          modAs[Q, categoryColumns]
	ReverseCategories modAs[Q, categoryColumns]
	Workspace         modAs[Q, workspaceColumns]
	Transactions      modAs[Q, transactionColumns]
}

func (j categoryJoins[Q]) aliasedAs(alias string) categoryJoins[Q] {
	return buildCategoryJoins[Q](buildCategoryColumns(alias), j.typ)
}

func buildCategoryJoins[Q dialect.Joinable](cols categoryColumns, typ string) categoryJoins[Q] {
	return categoryJoins[Q]{
		typ: typ,
		Category: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ID.EQ(cols.ParentID),
					))
				}

				return mods
			},
		},
		ReverseCategories: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ParentID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Workspace: modAs[Q, workspaceColumns]{
			c: Workspaces.Columns,
			f: func(to workspaceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Workspaces.Name().As(to.Alias())).On(
						to.ID.EQ(cols.WorkspaceID),
					))
				}

				return mods
			},
		},
		Transactions: modAs[Q, transactionColumns]{
			c: Transactions.Columns,
			f: func(to transactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transactions.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.CategoryID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
