// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	enums "github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen/dbenums"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Transaction is an object representing the database table.
type Transaction struct {
	ID                    uuid.UUID             `db:"id,pk" json:"id"`
	WorkspaceID           uuid.UUID             `db:"workspace_id" json:"workspace_id"`
	TransactionType       enums.TransactionType `db:"transaction_type" json:"transaction_type"`
	AccountID             null.Val[uuid.UUID]   `db:"account_id" json:"account_id"`
	CounterpartyAccountID null.Val[uuid.UUID]   `db:"counterparty_account_id" json:"counterparty_account_id"`
	CategoryID            null.Val[uuid.UUID]   `db:"category_id" json:"category_id"`
	Amount                decimal.Decimal       `db:"amount" json:"amount"`
	OccurredAt            time.Time             `db:"occurred_at" json:"occurred_at"`
	Description           null.Val[string]      `db:"description" json:"description"`

	R transactionR `db:"-" json:"-"`
}

// TransactionSlice is an alias for a slice of pointers to Transaction.
// This should almost always be used instead of []*Transaction.
type TransactionSlice []*Transaction

// Transactions contains methods to work with the transactions table
var Transactions = psql.NewTablex[*Transaction, TransactionSlice, *TransactionSetter]("", "transactions", buildTransactionColumns("transactions"))

// TransactionsQuery is a query on the transactions table
type TransactionsQuery = *psql.ViewQuery[*Transaction, TransactionSlice]

// transactionR is where relationships are stored.
type transactionR struct {
	Account             *Account   `json:"Account"`             // transactions.fk_transactions_account
	Category            *Category  `json:"Category"`            // transactions.fk_transactions_category
	CounterpartyAccount *Account   `json:"CounterpartyAccount"` // transactions.fk_transactions_counterparty_account
	Workspace           *Workspace `json:"Workspace"`           // transactions.fk_transactions_workspace
}

func buildTransactionColumns(alias string) transactionColumns {
	return transactionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "workspace_id", "transaction_type", "account_id", "counterparty_account_id", "category_id", "amount", "occurred_at", "description",
		).WithParent("transactions"),
		tableAlias:            alias,
		ID:                    psql.Quote(alias, "id"),
		WorkspaceID:           psql.Quote(alias, "workspace_id"),
		TransactionType:       psql.Quote(alias, "transaction_type"),
		AccountID:             psql.Quote(alias, "account_id"),
		CounterpartyAccountID: psql.Quote(alias, "counterparty_account_id"),
		CategoryID:            psql.Quote(alias, "category_id"),
		Amount:                psql.Quote(alias, "amount"),
		OccurredAt:            psql.Quote(alias, "occurred_at"),
		Description:           psql.Quote(alias, "description"),
	}
}

type transactionColumns struct {
	expr.ColumnsExpr
	tableAlias            string
	ID                    psql.Expression
	WorkspaceID           psql.Expression
	TransactionType       psql.Expression
	AccountID             psql.Expression
	CounterpartyAccountID psql.Expression
	CategoryID            psql.Expression
	Amount                psql.Expression
	OccurredAt            psql.Expression
	Description           psql.Expression
}

func (c transactionColumns) Alias() string {
	return c.tableAlias
}

func (transactionColumns) AliasedAs(alias string) transactionColumns {
	return buildTransactionColumns(alias)
}

// TransactionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TransactionSetter struct {
	ID                    omit.Val[uuid.UUID]             `db:"id,pk" json:"id"`
	WorkspaceID           omit.Val[uuid.UUID]             `db:"workspace_id" json:"workspace_id"`
	TransactionType       omit.Val[enums.TransactionType] `db:"transaction_type" json:"transaction_type"`
	AccountID             omitnull.Val[uuid.UUID]         `db:"account_id" json:"account_id"`
	CounterpartyAccountID omitnull.Val[uuid.UUID]         `db:"counterparty_account_id" json:"counterparty_account_id"`
	CategoryID            omitnull.Val[uuid.UUID]         `db:"category_id" json:"category_id"`
	Amount                omit.Val[decimal.Decimal]       `db:"amount" json:"amount"`
	OccurredAt            omit.Val[time.Time]             `db:"occurred_at" json:"occurred_at"`
	Description           omitnull.Val[string]            `db:"description" json:"description"`
}

func (s TransactionSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.WorkspaceID.IsValue() {
		vals = append(vals, "workspace_id")
	}
	if s.TransactionType.IsValue() {
		vals = append(vals, "transaction_type")
	}
	if !s.AccountID.IsUnset() {
		vals = append(vals, "account_id")
	}
	if !s.CounterpartyAccountID.IsUnset() {
		vals = append(vals, "counterparty_account_id")
	}
	if !s.CategoryID.IsUnset() {
		vals = append(vals, "category_id")
	}
	if s.Amount.IsValue() {
		vals = append(vals, "amount")
	}
	if s.OccurredAt.IsValue() {
		vals = append(vals, "occurred_at")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	return vals
}

func (s TransactionSetter) Overwrite(t *Transaction) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.WorkspaceID.IsValue() {
		t.WorkspaceID = s.WorkspaceID.MustGet()
	}
	if s.TransactionType.IsValue() {
		t.TransactionType = s.TransactionType.MustGet()
	}
	if !s.AccountID.IsUnset() {
		t.AccountID = s.AccountID.MustGetNull()
	}
	if !s.CounterpartyAccountID.IsUnset() {
		t.CounterpartyAccountID = s.CounterpartyAccountID.MustGetNull()
	}
	if !s.CategoryID.IsUnset() {
		t.CategoryID = s.CategoryID.MustGetNull()
	}
	if s.Amount.IsValue() {
		t.Amount = s.Amount.MustGet()
	}
	if s.OccurredAt.IsValue() {
		t.OccurredAt = s.OccurredAt.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
}

func (s *TransactionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Transactions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.WorkspaceID.IsValue() {
			vals[1] = psql.Arg(s.WorkspaceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.TransactionType.IsValue() {
			vals[2] = psql.Arg(s.TransactionType.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.AccountID.IsUnset() {
			vals[3] = psql.Arg(s.AccountID.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.CounterpartyAccountID.IsUnset() {
			vals[4] = psql.Arg(s.CounterpartyAccountID.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.CategoryID.IsUnset() {
			vals[5] = psql.Arg(s.CategoryID.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Amount.IsValue() {
			vals[6] = psql.Arg(s.Amount.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.OccurredAt.IsValue() {
			vals[7] = psql.Arg(s.OccurredAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[8] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TransactionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TransactionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.WorkspaceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "workspace_id")...),
			psql.Arg(s.WorkspaceID),
		}})
	}

	if s.TransactionType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "transaction_type")...),
			psql.Arg(s.TransactionType),
		}})
	}

	if !s.AccountID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_id")...),
			psql.Arg(s.AccountID),
		}})
	}

	if !s.CounterpartyAccountID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "counterparty_account_id")...),
			psql.Arg(s.CounterpartyAccountID),
		}})
	}

	if !s.CategoryID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category_id")...),
			psql.Arg(s.CategoryID),
		}})
	}

	if s.Amount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "amount")...),
			psql.Arg(s.Amount),
		}})
	}

	if s.OccurredAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "occurred_at")...),
			psql.Arg(s.OccurredAt),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	return exprs
}

// FindTransaction retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTransaction(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Transaction, error) {
	if len(cols) == 0 {
		return Transactions.Query(
			sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Transactions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TransactionExists checks the presence of a single record by primary key
func TransactionExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Transaction is retrieved from the database
func (o *Transaction) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transactions.AfterSelectHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Transactions.AfterInsertHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, TransactionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Transaction
func (o *Transaction) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Transaction) pkEQ() dialect.Expression {
	return psql.Quote("transactions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Transaction
func (o *Transaction) Update(ctx context.Context, exec bob.Executor, s *TransactionSetter) error {
	v, err := Transactions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Transaction record with an executor
func (o *Transaction) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Transactions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Transaction using the executor
func (o *Transaction) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TransactionSlice is retrieved from the database
func (o TransactionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transactions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Transactions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TransactionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("transactions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TransactionSlice) copyMatchingRows(from ...*Transaction) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TransactionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterUpdateHooks on the slice
				_, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TransactionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterDeleteHooks on the slice
				_, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TransactionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TransactionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transactions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TransactionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transactions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TransactionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Transactions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Account starts a query for related objects on accounts
func (o *Transaction) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Accounts.Columns.ID.EQ(psql.Arg(o.AccountID))),
	)...)
}

func (os TransactionSlice) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkAccountID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkAccountID = append(pkAccountID, o.AccountID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkAccountID), "uuid[]")),
	))

	return Accounts.Query(append(mods,
		sm.Where(psql.Group(Accounts.Columns.WorkspaceID, Accounts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Category starts a query for related objects on categories
func (o *Transaction) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.CategoryID))),
	)...)
}

func (os TransactionSlice) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkCategoryID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkCategoryID = append(pkCategoryID, o.CategoryID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkCategoryID), "uuid[]")),
	))

	return Categories.Query(append(mods,
		sm.Where(psql.Group(Categories.Columns.WorkspaceID, Categories.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// CounterpartyAccount starts a query for related objects on accounts
func (o *Transaction) CounterpartyAccount(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Accounts.Columns.ID.EQ(psql.Arg(o.CounterpartyAccountID))),
	)...)
}

func (os TransactionSlice) CounterpartyAccount(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkCounterpartyAccountID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkCounterpartyAccountID = append(pkCounterpartyAccountID, o.CounterpartyAccountID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkCounterpartyAccountID), "uuid[]")),
	))

	return Accounts.Query(append(mods,
		sm.Where(psql.Group(Accounts.Columns.WorkspaceID, Accounts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Workspace starts a query for related objects on workspaces
func (o *Transaction) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	return Workspaces.Query(append(mods,
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.WorkspaceID))),
	)...)
}

func (os TransactionSlice) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
	))

	return Workspaces.Query(append(mods,
		sm.Where(psql.Group(Workspaces.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachTransactionAccount0(ctx context.Context, exec bob.Executor, count int, transaction0 *Transaction, account1 *Account) (*Transaction, error) {
	setter := &TransactionSetter{
		WorkspaceID: omit.From(account1.WorkspaceID),
		AccountID:   omitnull.From(account1.ID),
	}

	err := transaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTransactionAccount0: %w", err)
	}

	return transaction0, nil
}

func (transaction0 *Transaction) InsertAccount(ctx context.Context, exec bob.Executor, related *AccountSetter) error {
	var err error

	account1, err := Accounts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTransactionAccount0(ctx, exec, 1, transaction0, account1)
	if err != nil {
		return err
	}

	transaction0.R.Account = account1

	account1.R.Transactions = append(account1.R.Transactions, transaction0)

	return nil
}

func (transaction0 *Transaction) AttachAccount(ctx context.Context, exec bob.Executor, account1 *Account) error {
	var err error

	_, err = attachTransactionAccount0(ctx, exec, 1, transaction0, account1)
	if err != nil {
		return err
	}

	transaction0.R.Account = account1

	account1.R.Transactions = append(account1.R.Transactions, transaction0)

	return nil
}

func attachTransactionCategory0(ctx context.Context, exec bob.Executor, count int, transaction0 *Transaction, category1 *Category) (*Transaction, error) {
	setter := &TransactionSetter{
		WorkspaceID: omit.From(category1.WorkspaceID),
		CategoryID:  omitnull.From(category1.ID),
	}

	err := transaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTransactionCategory0: %w", err)
	}

	return transaction0, nil
}

func (transaction0 *Transaction) InsertCategory(ctx context.Context, exec bob.Executor, related *CategorySetter) error {
	var err error

	category1, err := Categories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTransactionCategory0(ctx, exec, 1, transaction0, category1)
	if err != nil {
		return err
	}

	transaction0.R.Category = category1

	category1.R.Transactions = append(category1.R.Transactions, transaction0)

	return nil
}

func (transaction0 *Transaction) AttachCategory(ctx context.Context, exec bob.Executor, category1 *Category) error {
	var err error

	_, err = attachTransactionCategory0(ctx, exec, 1, transaction0, category1)
	if err != nil {
		return err
	}

	transaction0.R.Category = category1

	category1.R.Transactions = append(category1.R.Transactions, transaction0)

	return nil
}

func attachTransactionCounterpartyAccount0(ctx context.Context, exec bob.Executor, count int, transaction0 *Transaction, account1 *Account) (*Transaction, error) {
	setter := &TransactionSetter{
		WorkspaceID:           omit.From(account1.WorkspaceID),
		CounterpartyAccountID: omitnull.From(account1.ID),
	}

	err := transaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTransactionCounterpartyAccount0: %w", err)
	}

	return transaction0, nil
}

func (transaction0 *Transaction) InsertCounterpartyAccount(ctx context.Context, exec bob.Executor, related *AccountSetter) error {
	var err error

	account1, err := Accounts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTransactionCounterpartyAccount0(ctx, exec, 1, transaction0, account1)
	if err != nil {
		return err
	}

	transaction0.R.CounterpartyAccount = account1

	account1.R.CounterpartyTransactions = append(account1.R.CounterpartyTransactions, transaction0)

	return nil
}

func (transaction0 *Transaction) AttachCounterpartyAccount(ctx context.Context, exec bob.Executor, account1 *Account) error {
	var err error

	_, err = attachTransactionCounterpartyAccount0(ctx, exec, 1, transaction0, account1)
	if err != nil {
		return err
	}

	transaction0.R.CounterpartyAccount = account1

	account1.R.CounterpartyTransactions = append(account1.R.CounterpartyTransactions, transaction0)

	return nil
}

func attachTransactionWorkspace0(ctx context.Context, exec bob.Executor, count int, transaction0 *Transaction, workspace1 *Workspace) (*Transaction, error) {
	setter := &TransactionSetter{
		WorkspaceID: omit.From(workspace1.ID),
	}

	err := transaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTransactionWorkspace0: %w", err)
	}

	return transaction0, nil
}

func (transaction0 *Transaction) InsertWorkspace(ctx context.Context, exec bob.Executor, related *WorkspaceSetter) error {
	var err error

	workspace1, err := Workspaces.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTransactionWorkspace0(ctx, exec, 1, transaction0, workspace1)
	if err != nil {
		return err
	}

	transaction0.R.Workspace = workspace1

	workspace1.R.Transactions = append(workspace1.R.Transactions, transaction0)

	return nil
}

func (transaction0 *Transaction) AttachWorkspace(ctx context.Context, exec bob.Executor, workspace1 *Workspace) error {
	var err error

	_, err = attachTransactionWorkspace0(ctx, exec, 1, transaction0, workspace1)
	if err != nil {
		return err
	}

	transaction0.R.Workspace = workspace1

	workspace1.R.Transactions = append(workspace1.R.Transactions, transaction0)

	return nil
}

type transactionWhere[Q psql.Filterable] struct {
	ID                    psql.WhereMod[Q, uuid.UUID]
	WorkspaceID           psql.WhereMod[Q, uuid.UUID]
	TransactionType       psql.WhereMod[Q, enums.TransactionType]
	AccountID             psql.WhereNullMod[Q, uuid.UUID]
	CounterpartyAccountID psql.WhereNullMod[Q, uuid.UUID]
	CategoryID            psql.WhereNullMod[Q, uuid.UUID]
	Amount                psql.WhereMod[Q, decimal.Decimal]
	OccurredAt            psql.WhereMod[Q, time.Time]
	Description           psql.WhereNullMod[Q, string]
}

func (transactionWhere[Q]) AliasedAs(alias string) transactionWhere[Q] {
	return buildTransactionWhere[Q](buildTransactionColumns(alias))
}

func buildTransactionWhere[Q psql.Filterable](cols transactionColumns) transactionWhere[Q] {
	return transactionWhere[Q]{
		ID:                    psql.Where[Q, uuid.UUID](cols.ID),
		WorkspaceID:           psql.Where[Q, uuid.UUID](cols.WorkspaceID),
		TransactionType:       psql.Where[Q, enums.TransactionType](cols.TransactionType),
		AccountID:             psql.WhereNull[Q, uuid.UUID](cols.AccountID),
		CounterpartyAccountID: psql.WhereNull[Q, uuid.UUID](cols.CounterpartyAccountID),
		CategoryID:            psql.WhereNull[Q, uuid.UUID](cols.CategoryID),
		Amount:                psql.Where[Q, decimal.Decimal](cols.Amount),
		OccurredAt:            psql.Where[Q, time.Time](cols.OccurredAt),
		Description:           psql.WhereNull[Q, string](cols.Description),
	}
}

func (o *Transaction) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Account":
		rel, ok := retrieved.(*Account)
		if !ok {
			return fmt.Errorf("transaction cannot load %T as %q", retrieved, name)
		}

		o.R.Account = rel

		if rel != nil {
			rel.R.Transactions = TransactionSlice{o}
		}
		return nil
	case "Category":
		rel, ok := retrieved.(*Category)
		if !ok {
			return fmt.Errorf("transaction cannot load %T as %q", retrieved, name)
		}

		o.R.Category = rel

		if rel != nil {
			rel.R.Transactions = TransactionSlice{o}
		}
		return nil
	case "CounterpartyAccount":
		rel, ok := retrieved.(*Account)
		if !ok {
			return fmt.Errorf("transaction cannot load %T as %q", retrieved, name)
		}

		o.R.CounterpartyAccount = rel

		if rel != nil {
			rel.R.CounterpartyTransactions = TransactionSlice{o}
		}
		return nil
	case "Workspace":
		rel, ok := retrieved.(*Workspace)
		if !ok {
			return fmt.Errorf("transaction cannot load %T as %q", retrieved, name)
		}

		o.R.Workspace = rel

		if rel != nil {
			rel.R.Transactions = TransactionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("transaction has no relationship %q", name)
	}
}

type transactionPreloader struct {
	Account             func(...psql.PreloadOption) psql.Preloader
	Category            func(...psql.PreloadOption) psql.Preloader
	CounterpartyAccount func(...psql.PreloadOption) psql.Preloader
	Workspace           func(...psql.PreloadOption) psql.Preloader
}

func buildTransactionPreloader() transactionPreloader {
	return transactionPreloader{
		Account: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Account, AccountSlice](psql.PreloadRel{
				Name: "Account",
				Sides: []psql.PreloadSide{
					{
						From:        Transactions,
						To:          Accounts,
						FromColumns: []string{"workspace_id", "account_id"},
						ToColumns:   []string{"workspace_id", "id"},
					},
				},
			}, Accounts.Columns.Names(), opts...)
		},
		Category: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Category, CategorySlice](psql.PreloadRel{
				Name: "Category",
				Sides: []psql.PreloadSide{
					{
						From:        Transactions,
						To:          Categories,
						FromColumns: []string{"workspace_id", "category_id"},
						ToColumns:   []string{"workspace_id", "id"},
					},
				},
			}, Categories.Columns.Names(), opts...)
		},
		CounterpartyAccount: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Account, AccountSlice](psql.PreloadRel{
				Name: "CounterpartyAccount",
				Sides: []psql.PreloadSide{
					{
						From:        Transactions,
						To:          Accounts,
						FromColumns: []string{"workspace_id", "counterparty_account_id"},
						ToColumns:   []string{"workspace_id", "id"},
					},
				},
			}, Accounts.Columns.Names(), opts...)
		},
		Workspace: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Workspace, WorkspaceSlice](psql.PreloadRel{
				Name: "Workspace",
				Sides: []psql.PreloadSide{
					{
						From:        Transactions,
						To:          Workspaces,
						FromColumns: []string{"workspace_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Workspaces.Columns.Names(), opts...)
		},
	}
}

type transactionThenLoader[Q orm.Loadable] struct {
	Account             func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Category            func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CounterpartyAccount func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Workspace           func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTransactionThenLoader[Q orm.Loadable]() transactionThenLoader[Q] {
	type AccountLoadInterface interface {
		LoadAccount(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CategoryLoadInterface interface {
		LoadCategory(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CounterpartyAccountLoadInterface interface {
		LoadCounterpartyAccount(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type WorkspaceLoadInterface interface {
		LoadWorkspace(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return transactionThenLoader[Q]{
		Account: thenLoadBuilder[Q](
			"Account",
			func(ctx context.Context, exec bob.Executor, retrieved AccountLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAccount(ctx, exec, mods...)
			},
		),
		Category: thenLoadBuilder[Q](
			"Category",
			func(ctx context.Context, exec bob.Executor, retrieved CategoryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCategory(ctx, exec, mods...)
			},
		),
		CounterpartyAccount: thenLoadBuilder[Q](
			"CounterpartyAccount",
			func(ctx context.Context, exec bob.Executor, retrieved CounterpartyAccountLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCounterpartyAccount(ctx, exec, mods...)
			},
		),
		Workspace: thenLoadBuilder[Q](
			"Workspace",
			func(ctx context.Context, exec bob.Executor, retrieved WorkspaceLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadWorkspace(ctx, exec, mods...)
			},
		),
	}
}

// LoadAccount loads the transaction's Account into the .R struct
func (o *Transaction) LoadAccount(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Account = nil

	related, err := o.Account(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Transactions = TransactionSlice{o}

	o.R.Account = related
	return nil
}

// LoadAccount loads the transaction's Account into the .R struct
func (os TransactionSlice) LoadAccount(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	accounts, err := os.Account(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range accounts {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}
			if !o.AccountID.IsValue() {
				continue
			}

			if !(o.AccountID.IsValue() && o.AccountID.MustGet() == rel.ID) {
				continue
			}

			rel.R.Transactions = append(rel.R.Transactions, o)

			o.R.Account = rel
			break
		}
	}

	return nil
}

// LoadCategory loads the transaction's Category into the .R struct
func (o *Transaction) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Category = nil

	related, err := o.Category(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Transactions = TransactionSlice{o}

	o.R.Category = related
	return nil
}

// LoadCategory loads the transaction's Category into the .R struct
func (os TransactionSlice) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Category(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range categories {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}
			if !o.CategoryID.IsValue() {
				continue
			}

			if !(o.CategoryID.IsValue() && o.CategoryID.MustGet() == rel.ID) {
				continue
			}

			rel.R.Transactions = append(rel.R.Transactions, o)

			o.R.Category = rel
			break
		}
	}

	return nil
}

// LoadCounterpartyAccount loads the transaction's CounterpartyAccount into the .R struct
func (o *Transaction) LoadCounterpartyAccount(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CounterpartyAccount = nil

	related, err := o.CounterpartyAccount(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CounterpartyTransactions = TransactionSlice{o}

	o.R.CounterpartyAccount = related
	return nil
}

// LoadCounterpartyAccount loads the transaction's CounterpartyAccount into the .R struct
func (os TransactionSlice) LoadCounterpartyAccount(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	accounts, err := os.CounterpartyAccount(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range accounts {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}
			if !o.CounterpartyAccountID.IsValue() {
				continue
			}

			if !(o.CounterpartyAccountID.IsValue() && o.CounterpartyAccountID.MustGet() == rel.ID) {
				continue
			}

			rel.R.CounterpartyTransactions = append(rel.R.CounterpartyTransactions, o)

			o.R.CounterpartyAccount = rel
			break
		}
	}

	return nil
}

// LoadWorkspace loads the transaction's Workspace into the .R struct
func (o *Transaction) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Workspace = nil

	related, err := o.Workspace(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Transactions = TransactionSlice{o}

	o.R.Workspace = related
	return nil
}

// LoadWorkspace loads the transaction's Workspace into the .R struct
func (os TransactionSlice) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	workspaces, err := os.Workspace(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range workspaces {

			if !(o.WorkspaceID == rel.ID) {
				continue
			}

			rel.R.Transactions = append(rel.R.Transactions, o)

			o.R.Workspace = rel
			break
		}
	}

	return nil
}

type transactionJoins[Q dialect.Joinable] struct {
	typ                 string
	Account             modAs[Q, accountColumns]
	Category            modAs[Q, categoryColumns]
	CounterpartyAccount modAs[Q, accountColumns]
	Workspace           modAs[Q, workspaceColumns]
}

func (j transactionJoins[Q]) aliasedAs(alias string) transactionJoins[Q] {
	return buildTransactionJoins[Q](buildTransactionColumns(alias), j.typ)
}

func buildTransactionJoins[Q dialect.Joinable](cols transactionColumns, typ string) transactionJoins[Q] {
	return transactionJoins[Q]{
		typ: typ,
		Account: modAs[Q, accountColumns]{
			c: Accounts.Columns,
			f: func(to accountColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Accounts.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ID.EQ(cols.AccountID),
					))
				}

				return mods
			},
		},
		Category: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ID.EQ(cols.CategoryID),
					))
				}

				return mods
			},
		},
		CounterpartyAccount: modAs[Q, accountColumns]{
			c: Accounts.Columns,
			f: func(to accountColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Accounts.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ID.EQ(cols.CounterpartyAccountID),
					))
				}

				return mods
			},
		},
		Workspace: modAs[Q, workspaceColumns]{
			c: Workspaces.Columns,
			f: func(to workspaceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Workspaces.Name().As(to.Alias())).On(
						to.ID.EQ(cols.WorkspaceID),
					))
				}

				return mods
			},
		},
	}
}
