// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Workspace is an object representing the database table.
type Workspace struct {
	ID   uuid.UUID `db:"id,pk" json:"id"`
	Name string    `db:"name" json:"name"`

	R workspaceR `db:"-" json:"-"`
}

// WorkspaceSlice is an alias for a slice of pointers to Workspace.
// This should almost always be used instead of []*Workspace.
type WorkspaceSlice []*Workspace

// Workspaces contains methods to work with the workspaces table
var Workspaces = psql.NewTablex[*Workspace, WorkspaceSlice, *WorkspaceSetter]("", "workspaces", buildWorkspaceColumns("workspaces"))

// WorkspacesQuery is a query on the workspaces table
type WorkspacesQuery = *psql.ViewQuery[*Workspace, WorkspaceSlice]

// workspaceR is where relationships are stored.
type workspaceR struct {
	Accounts     AccountSlice     `json:"Accounts"`     // accounts.fk_accounts_workspace
	Categories   CategorySlice    `json:"Categories"`   // categories.fk_categories_workspace
	Members      MemberSlice      `json:"Members"`      // members.fk_members_workspace
	Transactions TransactionSlice `json:"Transactions"` // transactions.fk_transactions_workspace
}

func buildWorkspaceColumns(alias string) workspaceColumns {
	return workspaceColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name",
		).WithParent("workspaces"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
	}
}

type workspaceColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
}

func (c workspaceColumns) Alias() string {
	return c.tableAlias
}

func (workspaceColumns) AliasedAs(alias string) workspaceColumns {
	return buildWorkspaceColumns(alias)
}

// WorkspaceSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type WorkspaceSetter struct {
	ID   omit.Val[uuid.UUID] `db:"id,pk" json:"id"`
	Name omit.Val[string]    `db:"name" json:"name"`
}

func (s WorkspaceSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	return vals
}

func (s WorkspaceSetter) Overwrite(t *Workspace) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
}

func (s *WorkspaceSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Workspaces.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s WorkspaceSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s WorkspaceSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	return exprs
}

// FindWorkspace retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindWorkspace(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Workspace, error) {
	if len(cols) == 0 {
		return Workspaces.Query(
			sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Workspaces.Query(
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Workspaces.Columns.Only(cols...)),
	).One(ctx, exec)
}

// WorkspaceExists checks the presence of a single record by primary key
func WorkspaceExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Workspaces.Query(
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Workspace is retrieved from the database
func (o *Workspace) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Workspaces.AfterSelectHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Workspaces.AfterInsertHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Workspaces.AfterUpdateHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Workspaces.AfterDeleteHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Workspace
func (o *Workspace) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Workspace) pkEQ() dialect.Expression {
	return psql.Quote("workspaces", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Workspace
func (o *Workspace) Update(ctx context.Context, exec bob.Executor, s *WorkspaceSetter) error {
	v, err := Workspaces.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Workspace record with an executor
func (o *Workspace) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Workspaces.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Workspace using the executor
func (o *Workspace) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Workspaces.Query(
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after WorkspaceSlice is retrieved from the database
func (o WorkspaceSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Workspaces.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Workspaces.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Workspaces.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Workspaces.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o WorkspaceSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("workspaces", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o WorkspaceSlice) copyMatchingRows(from ...*Workspace) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o WorkspaceSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Workspaces.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Workspace:
				o.copyMatchingRows(retrieved)
			case []*Workspace:
				o.copyMatchingRows(retrieved...)
			case WorkspaceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Workspace or a slice of Workspace
				// then run the AfterUpdateHooks on the slice
				_, err = Workspaces.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o WorkspaceSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Workspaces.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Workspace:
				o.copyMatchingRows(retrieved)
			case []*Workspace:
				o.copyMatchingRows(retrieved...)
			case WorkspaceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Workspace or a slice of Workspace
				// then run the AfterDeleteHooks on the slice
				_, err = Workspaces.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o WorkspaceSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals WorkspaceSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Workspaces.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o WorkspaceSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Workspaces.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o WorkspaceSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Workspaces.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Accounts starts a query for related objects on accounts
func (o *Workspace) Accounts(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) Accounts(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Accounts.Query(append(mods,
		sm.Where(psql.Group(Accounts.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

// Categories starts a query for related objects on categories
func (o *Workspace) Categories(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) Categories(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Categories.Query(append(mods,
		sm.Where(psql.Group(Categories.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

// Members starts a query for related objects on members
func (o *Workspace) Members(mods ...bob.Mod[*dialect.SelectQuery]) MembersQuery {
	return Members.Query(append(mods,
		sm.Where(Members.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) Members(mods ...bob.Mod[*dialect.SelectQuery]) MembersQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Members.Query(append(mods,
		sm.Where(psql.Group(Members.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

// Transactions starts a query for related objects on transactions
func (o *Workspace) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Transactions.Query(append(mods,
		sm.Where(psql.Group(Transactions.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

func insertWorkspaceAccounts0(ctx context.Context, exec bob.Executor, accounts1 []*AccountSetter, workspace0 *Workspace) (AccountSlice, error) {
	for i := range accounts1 {
		accounts1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := Accounts.Insert(bob.ToMods(accounts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceAccounts0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceAccounts0(ctx context.Context, exec bob.Executor, count int, accounts1 AccountSlice, workspace0 *Workspace) (AccountSlice, error) {
	setter := &AccountSetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := accounts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceAccounts0: %w", err)
	}

	return accounts1, nil
}

func (workspace0 *Workspace) InsertAccounts(ctx context.Context, exec bob.Executor, related ...*AccountSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	accounts1, err := insertWorkspaceAccounts0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Accounts = append(workspace0.R.Accounts, accounts1...)

	for _, rel := range accounts1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachAccounts(ctx context.Context, exec bob.Executor, related ...*Account) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	accounts1 := AccountSlice(related)

	_, err = attachWorkspaceAccounts0(ctx, exec, len(related), accounts1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Accounts = append(workspace0.R.Accounts, accounts1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

func insertWorkspaceCategories0(ctx context.Context, exec bob.Executor, categories1 []*CategorySetter, workspace0 *Workspace) (CategorySlice, error) {
	for i := range categories1 {
		categories1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := Categories.Insert(bob.ToMods(categories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceCategories0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceCategories0(ctx context.Context, exec bob.Executor, count int, categories1 CategorySlice, workspace0 *Workspace) (CategorySlice, error) {
	setter := &CategorySetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := categories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceCategories0: %w", err)
	}

	return categories1, nil
}

func (workspace0 *Workspace) InsertCategories(ctx context.Context, exec bob.Executor, related ...*CategorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	categories1, err := insertWorkspaceCategories0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Categories = append(workspace0.R.Categories, categories1...)

	for _, rel := range categories1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachCategories(ctx context.Context, exec bob.Executor, related ...*Category) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	categories1 := CategorySlice(related)

	_, err = attachWorkspaceCategories0(ctx, exec, len(related), categories1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Categories = append(workspace0.R.Categories, categories1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

func insertWorkspaceMembers0(ctx context.Context, exec bob.Executor, members1 []*MemberSetter, workspace0 *Workspace) (MemberSlice, error) {
	for i := range members1 {
		members1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := Members.Insert(bob.ToMods(members1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceMembers0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceMembers0(ctx context.Context, exec bob.Executor, count int, members1 MemberSlice, workspace0 *Workspace) (MemberSlice, error) {
	setter := &MemberSetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := members1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceMembers0: %w", err)
	}

	return members1, nil
}

func (workspace0 *Workspace) InsertMembers(ctx context.Context, exec bob.Executor, related ...*MemberSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	members1, err := insertWorkspaceMembers0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Members = append(workspace0.R.Members, members1...)

	for _, rel := range members1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachMembers(ctx context.Context, exec bob.Executor, related ...*Member) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	members1 := MemberSlice(related)

	_, err = attachWorkspaceMembers0(ctx, exec, len(related), members1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Members = append(workspace0.R.Members, members1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

func insertWorkspaceTransactions0(ctx context.Context, exec bob.Executor, transactions1 []*TransactionSetter, workspace0 *Workspace) (TransactionSlice, error) {
	for i := range transactions1 {
		transactions1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := Transactions.Insert(bob.ToMods(transactions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceTransactions0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceTransactions0(ctx context.Context, exec bob.Executor, count int, transactions1 TransactionSlice, workspace0 *Workspace) (TransactionSlice, error) {
	setter := &TransactionSetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := transactions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceTransactions0: %w", err)
	}

	return transactions1, nil
}

func (workspace0 *Workspace) InsertTransactions(ctx context.Context, exec bob.Executor, related ...*TransactionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	transactions1, err := insertWorkspaceTransactions0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Transactions = append(workspace0.R.Transactions, transactions1...)

	for _, rel := range transactions1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachTransactions(ctx context.Context, exec bob.Executor, related ...*Transaction) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	transactions1 := TransactionSlice(related)

	_, err = attachWorkspaceTransactions0(ctx, exec, len(related), transactions1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Transactions = append(workspace0.R.Transactions, transactions1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

type workspaceWhere[Q psql.Filterable] struct {
	ID   psql.WhereMod[Q, uuid.UUID]
	Name psql.WhereMod[Q, string]
}

func (workspaceWhere[Q]) AliasedAs(alias string) workspaceWhere[Q] {
	return buildWorkspaceWhere[Q](buildWorkspaceColumns(alias))
}

func buildWorkspaceWhere[Q psql.Filterable](cols workspaceColumns) workspaceWhere[Q] {
	return workspaceWhere[Q]{
		ID:   psql.Where[Q, uuid.UUID](cols.ID),
		Name: psql.Where[Q, string](cols.Name),
	}
}

func (o *Workspace) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Accounts":
		rels, ok := retrieved.(AccountSlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.Accounts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	case "Categories":
		rels, ok := retrieved.(CategorySlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.Categories = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	case "Members":
		rels, ok := retrieved.(MemberSlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.Members = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	case "Transactions":
		rels, ok := retrieved.(TransactionSlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.Transactions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	default:
		return fmt.Errorf("workspace has no relationship %q", name)
	}
}

type workspacePreloader struct{}

func buildWorkspacePreloader() workspacePreloader {
	return workspacePreloader{}
}

type workspaceThenLoader[Q orm.Loadable] struct {
	Accounts     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Categories   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Members      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transactions func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildWorkspaceThenLoader[Q orm.Loadable]() workspaceThenLoader[Q] {
	type AccountsLoadInterface interface {
		LoadAccounts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CategoriesLoadInterface interface {
		LoadCategories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MembersLoadInterface interface {
		LoadMembers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TransactionsLoadInterface interface {
		LoadTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return workspaceThenLoader[Q]{
		Accounts: thenLoadBuilder[Q](
			"Accounts",
			func(ctx context.Context, exec bob.Executor, retrieved AccountsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAccounts(ctx, exec, mods...)
			},
		),
		Categories: thenLoadBuilder[Q](
			"Categories",
			func(ctx context.Context, exec bob.Executor, retrieved CategoriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCategories(ctx, exec, mods...)
			},
		),
		Members: thenLoadBuilder[Q](
			"Members",
			func(ctx context.Context, exec bob.Executor, retrieved MembersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMembers(ctx, exec, mods...)
			},
		),
		Transactions: thenLoadBuilder[Q](
			"Transactions",
			func(ctx context.Context, exec bob.Executor, retrieved TransactionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTransactions(ctx, exec, mods...)
			},
		),
	}
}

// LoadAccounts loads the workspace's Accounts into the .R struct
func (o *Workspace) LoadAccounts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Accounts = nil

	related, err := o.Accounts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.Accounts = related
	return nil
}

// LoadAccounts loads the workspace's Accounts into the .R struct
func (os WorkspaceSlice) LoadAccounts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	accounts, err := os.Accounts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Accounts = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range accounts {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.Accounts = append(o.R.Accounts, rel)
		}
	}

	return nil
}

// LoadCategories loads the workspace's Categories into the .R struct
func (o *Workspace) LoadCategories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Categories = nil

	related, err := o.Categories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.Categories = related
	return nil
}

// LoadCategories loads the workspace's Categories into the .R struct
func (os WorkspaceSlice) LoadCategories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Categories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Categories = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range categories {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.Categories = append(o.R.Categories, rel)
		}
	}

	return nil
}

// LoadMembers loads the workspace's Members into the .R struct
func (o *Workspace) LoadMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Members = nil

	related, err := o.Members(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.Members = related
	return nil
}

// LoadMembers loads the workspace's Members into the .R struct
func (os WorkspaceSlice) LoadMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	members, err := os.Members(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Members = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range members {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.Members = append(o.R.Members, rel)
		}
	}

	return nil
}

// LoadTransactions loads the workspace's Transactions into the .R struct
func (o *Workspace) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transactions = nil

	related, err := o.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.Transactions = related
	return nil
}

// LoadTransactions loads the workspace's Transactions into the .R struct
func (os WorkspaceSlice) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transactions, err := os.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Transactions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range transactions {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.Transactions = append(o.R.Transactions, rel)
		}
	}

	return nil
}

type workspaceJoins[Q dialect.Joinable] struct {
	typ          string
	Accounts     modAs[Q, accountColumns]
	Categories   modAs[Q, categoryColumns]
	Members      modAs[Q, memberColumns]
	Transactions modAs[Q, transactionColumns]
}

func (j workspaceJoins[Q]) aliasedAs(alias string) workspaceJoins[Q] {
	return buildWorkspaceJoins[Q](buildWorkspaceColumns(alias), j.typ)
}

func buildWorkspaceJoins[Q dialect.Joinable](cols workspaceColumns, typ string) workspaceJoins[Q] {
	return workspaceJoins[Q]{
		typ: typ,
		Accounts: modAs[Q, accountColumns]{
			c: Accounts.Columns,
			f: func(to accountColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Accounts.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Categories: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Members: modAs[Q, memberColumns]{
			c: Members.Columns,
			f: func(to memberColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Members.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Transactions: modAs[Q, transactionColumns]{
			c: Transactions.Columns,
			f: func(to transactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transactions.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
