/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ワークスペース一覧取得 */
    get: operations["listWorkspaces"];
    put?: never;
    /** ワークスペース作成 */
    post: operations["createWorkspace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** ワークスペース詳細取得 */
    get: operations["getWorkspace"];
    /** ワークスペース更新 */
    put: operations["updateWorkspace"];
    post?: never;
    /** ワークスペース削除 */
    delete: operations["deleteWorkspace"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/members": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** メンバー一覧取得 */
    get: operations["listMembers"];
    put?: never;
    /** メンバー追加 */
    post: operations["createMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/members/{memberId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        memberId: string;
      };
      cookie?: never;
    };
    /** メンバー詳細取得 */
    get: operations["getMember"];
    /** メンバー更新 */
    put: operations["updateMember"];
    post?: never;
    /** メンバー削除 */
    delete: operations["deleteMember"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** 口座一覧取得 */
    get: operations["listAccounts"];
    put?: never;
    /** 口座作成 */
    post: operations["createAccount"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/accounts/{accountId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        accountId: string;
      };
      cookie?: never;
    };
    /** 口座詳細取得 */
    get: operations["getAccount"];
    /** 口座更新 */
    put: operations["updateAccount"];
    post?: never;
    /** 口座削除 */
    delete: operations["deleteAccount"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/categories": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** カテゴリ一覧取得 */
    get: operations["listCategories"];
    put?: never;
    /** カテゴリ作成 */
    post: operations["createCategory"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/categories/{categoryId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        categoryId: string;
      };
      cookie?: never;
    };
    /** カテゴリ詳細取得 */
    get: operations["getCategory"];
    /** カテゴリ更新 */
    put: operations["updateCategory"];
    post?: never;
    /** カテゴリ削除 */
    delete: operations["deleteCategory"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** 取引一覧取得（フィルタ可能） */
    get: operations["listTransactions"];
    put?: never;
    /** 取引作成 */
    post: operations["createTransaction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/transactions/{txId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        txId: string;
      };
      cookie?: never;
    };
    /** 取引詳細取得 */
    get: operations["getTransaction"];
    /** 取引更新 */
    put: operations["updateTransaction"];
    post?: never;
    /** 取引削除 */
    delete: operations["deleteTransaction"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/reports/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** ダッシュボード概要取得 */
    get: operations["getDashboard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/reports/category-expenses": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** カテゴリ別支出集計取得 */
    get: operations["getCategoryExpenses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{wsId}/reports/account-balances": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    /** 口座別残高サマリ取得 */
    get: operations["getAccountBalances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Workspace: {
      /** Format: uuid */
      id: string;
      name: string;
    };
    CreateWorkspaceRequest: {
      name: string;
    };
    UpdateWorkspaceRequest: {
      name: string;
    };
    /** @enum {string} */
    MemberRole: "owner" | "editor" | "viewer";
    Member: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      /** Format: email */
      email: string;
      displayName: string;
      role: components["schemas"]["MemberRole"];
    };
    CreateMemberRequest: {
      /** Format: email */
      email: string;
      displayName: string;
      role: components["schemas"]["MemberRole"];
    };
    UpdateMemberRequest: {
      displayName: string;
      role: components["schemas"]["MemberRole"];
    };
    /** @enum {string} */
    AccountType: "cash" | "bank" | "credit_card" | "e_money" | "investment";
    Account: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      name: string;
      accountType: components["schemas"]["AccountType"];
      /** @description Decimal amount (e.g. "1000.00") */
      initialBalance: string;
    };
    CreateAccountRequest: {
      name: string;
      accountType: components["schemas"]["AccountType"];
      /** @description Decimal amount (e.g. "1000.00") */
      initialBalance: string;
    };
    UpdateAccountRequest: {
      name: string;
      accountType: components["schemas"]["AccountType"];
    };
    /** @enum {string} */
    CategoryType: "income" | "expense";
    Category: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      name: string;
      categoryType: components["schemas"]["CategoryType"];
      /** Format: uuid */
      parentId?: string | null;
    };
    CreateCategoryRequest: {
      name: string;
      categoryType: components["schemas"]["CategoryType"];
      /** Format: uuid */
      parentId?: string | null;
    };
    UpdateCategoryRequest: {
      name: string;
      categoryType: components["schemas"]["CategoryType"];
      /** Format: uuid */
      parentId?: string | null;
    };
    /** @enum {string} */
    TransactionType: "income" | "expense" | "transfer";
    Transaction: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      transactionType: components["schemas"]["TransactionType"];
      /** Format: uuid */
      accountId?: string | null;
      /** Format: uuid */
      counterpartyAccountId?: string | null;
      /** Format: uuid */
      categoryId?: string | null;
      /** @description Decimal amount (e.g. "1000.00") */
      amount: string;
      /** Format: date-time */
      occurredAt: string;
      description?: string | null;
    };
    CreateTransactionRequest: {
      transactionType: components["schemas"]["TransactionType"];
      /** Format: uuid */
      accountId?: string | null;
      /** Format: uuid */
      counterpartyAccountId?: string | null;
      /** Format: uuid */
      categoryId?: string | null;
      /** @description Decimal amount (e.g. "1000.00") */
      amount: string;
      /** Format: date-time */
      occurredAt: string;
      description?: string | null;
    };
    UpdateTransactionRequest: {
      transactionType: components["schemas"]["TransactionType"];
      /** Format: uuid */
      accountId?: string | null;
      /** Format: uuid */
      counterpartyAccountId?: string | null;
      /** Format: uuid */
      categoryId?: string | null;
      /** @description Decimal amount (e.g. "1000.00") */
      amount: string;
      /** Format: date-time */
      occurredAt: string;
      description?: string | null;
    };
    DashboardReport: {
      /** Format: uuid */
      workspaceId: string;
      /** @description Decimal amount */
      totalIncome: string;
      /** @description Decimal amount */
      totalExpense: string;
      /** @description Decimal amount */
      netFlow: string;
      /** Format: int64 */
      transactionCount: number;
    };
    CategoryExpenseItem: {
      /** Format: uuid */
      categoryId: string;
      categoryName: string;
      /** @description Decimal amount */
      totalExpense: string;
    };
    AccountBalanceItem: {
      /** Format: uuid */
      accountId: string;
      accountName: string;
      accountType: components["schemas"]["AccountType"];
      /** @description Decimal amount */
      currentBalance: string;
    };
    ErrorResponse: {
      message: string;
      code?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listWorkspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Workspace"][];
        };
      };
    };
  };
  createWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Workspace"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Workspace"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Workspace"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"][];
        };
      };
    };
  };
  createMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMemberRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        memberId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        memberId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMemberRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        memberId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listAccounts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"][];
        };
      };
    };
  };
  createAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAccountRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        accountId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        accountId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        accountId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listCategories: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"][];
        };
      };
    };
  };
  createCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCategoryRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        categoryId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        categoryId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        categoryId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listTransactions: {
    parameters: {
      query?: {
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transaction"][];
        };
      };
    };
  };
  createTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTransactionRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transaction"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        txId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transaction"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        txId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTransactionRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transaction"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        wsId: string;
        txId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getDashboard: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DashboardReport"];
        };
      };
    };
  };
  getCategoryExpenses: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryExpenseItem"][];
        };
      };
    };
  };
  getAccountBalances: {
    parameters: {
      query: {
        asOf: string;
      };
      header?: never;
      path: {
        wsId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountBalanceItem"][];
        };
      };
    };
  };
}
