// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/google/uuid"
	"github.com/o-ga09/vite-8-sample-app/internal/repository"
	"github.com/o-ga09/vite-8-sample-app/queries"
	"github.com/stephenafamo/bob"
	"sync"
	"time"
)

// Ensure, that ReportRepositoryMock does implement repository.ReportRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.ReportRepository = &ReportRepositoryMock{}

// ReportRepositoryMock is a mock implementation of repository.ReportRepository.
//
//	func TestSomethingThatUsesReportRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ReportRepository
//		mockedReportRepository := &ReportRepositoryMock{
//			GetAccountBalanceSummaryFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, asOf time.Time) ([]queries.GetAccountBalanceSummaryRow, error) {
//				panic("mock out the GetAccountBalanceSummary method")
//			},
//			GetCategoryExpenseSummaryFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) ([]queries.GetCategoryExpenseSummaryRow, error) {
//				panic("mock out the GetCategoryExpenseSummary method")
//			},
//			GetWorkspaceDashboardFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) ([]queries.GetWorkspaceDashboardRow, error) {
//				panic("mock out the GetWorkspaceDashboard method")
//			},
//		}
//
//		// use mockedReportRepository in code that requires repository.ReportRepository
//		// and then make assertions.
//
//	}
type ReportRepositoryMock struct {
	// GetAccountBalanceSummaryFunc mocks the GetAccountBalanceSummary method.
	GetAccountBalanceSummaryFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, asOf time.Time) ([]queries.GetAccountBalanceSummaryRow, error)

	// GetCategoryExpenseSummaryFunc mocks the GetCategoryExpenseSummary method.
	GetCategoryExpenseSummaryFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) ([]queries.GetCategoryExpenseSummaryRow, error)

	// GetWorkspaceDashboardFunc mocks the GetWorkspaceDashboard method.
	GetWorkspaceDashboardFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) ([]queries.GetWorkspaceDashboardRow, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetAccountBalanceSummary holds details about calls to the GetAccountBalanceSummary method.
		GetAccountBalanceSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
			// AsOf is the asOf argument value.
			AsOf time.Time
		}
		// GetCategoryExpenseSummary holds details about calls to the GetCategoryExpenseSummary method.
		GetCategoryExpenseSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetWorkspaceDashboard holds details about calls to the GetWorkspaceDashboard method.
		GetWorkspaceDashboard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
	}
	lockGetAccountBalanceSummary  sync.RWMutex
	lockGetCategoryExpenseSummary sync.RWMutex
	lockGetWorkspaceDashboard     sync.RWMutex
}

// GetAccountBalanceSummary calls GetAccountBalanceSummaryFunc.
func (mock *ReportRepositoryMock) GetAccountBalanceSummary(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, asOf time.Time) ([]queries.GetAccountBalanceSummaryRow, error) {
	if mock.GetAccountBalanceSummaryFunc == nil {
		panic("ReportRepositoryMock.GetAccountBalanceSummaryFunc: method is nil but ReportRepository.GetAccountBalanceSummary was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		AsOf        time.Time
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
		AsOf:        asOf,
	}
	mock.lockGetAccountBalanceSummary.Lock()
	mock.calls.GetAccountBalanceSummary = append(mock.calls.GetAccountBalanceSummary, callInfo)
	mock.lockGetAccountBalanceSummary.Unlock()
	return mock.GetAccountBalanceSummaryFunc(ctx, exec, workspaceID, asOf)
}

// GetAccountBalanceSummaryCalls gets all the calls that were made to GetAccountBalanceSummary.
// Check the length with:
//
//	len(mockedReportRepository.GetAccountBalanceSummaryCalls())
func (mock *ReportRepositoryMock) GetAccountBalanceSummaryCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
	AsOf        time.Time
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		AsOf        time.Time
	}
	mock.lockGetAccountBalanceSummary.RLock()
	calls = mock.calls.GetAccountBalanceSummary
	mock.lockGetAccountBalanceSummary.RUnlock()
	return calls
}

// GetCategoryExpenseSummary calls GetCategoryExpenseSummaryFunc.
func (mock *ReportRepositoryMock) GetCategoryExpenseSummary(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) ([]queries.GetCategoryExpenseSummaryRow, error) {
	if mock.GetCategoryExpenseSummaryFunc == nil {
		panic("ReportRepositoryMock.GetCategoryExpenseSummaryFunc: method is nil but ReportRepository.GetCategoryExpenseSummary was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		From        time.Time
		To          time.Time
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
		From:        from,
		To:          to,
	}
	mock.lockGetCategoryExpenseSummary.Lock()
	mock.calls.GetCategoryExpenseSummary = append(mock.calls.GetCategoryExpenseSummary, callInfo)
	mock.lockGetCategoryExpenseSummary.Unlock()
	return mock.GetCategoryExpenseSummaryFunc(ctx, exec, workspaceID, from, to)
}

// GetCategoryExpenseSummaryCalls gets all the calls that were made to GetCategoryExpenseSummary.
// Check the length with:
//
//	len(mockedReportRepository.GetCategoryExpenseSummaryCalls())
func (mock *ReportRepositoryMock) GetCategoryExpenseSummaryCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
	From        time.Time
	To          time.Time
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		From        time.Time
		To          time.Time
	}
	mock.lockGetCategoryExpenseSummary.RLock()
	calls = mock.calls.GetCategoryExpenseSummary
	mock.lockGetCategoryExpenseSummary.RUnlock()
	return calls
}

// GetWorkspaceDashboard calls GetWorkspaceDashboardFunc.
func (mock *ReportRepositoryMock) GetWorkspaceDashboard(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) ([]queries.GetWorkspaceDashboardRow, error) {
	if mock.GetWorkspaceDashboardFunc == nil {
		panic("ReportRepositoryMock.GetWorkspaceDashboardFunc: method is nil but ReportRepository.GetWorkspaceDashboard was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		From        time.Time
		To          time.Time
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
		From:        from,
		To:          to,
	}
	mock.lockGetWorkspaceDashboard.Lock()
	mock.calls.GetWorkspaceDashboard = append(mock.calls.GetWorkspaceDashboard, callInfo)
	mock.lockGetWorkspaceDashboard.Unlock()
	return mock.GetWorkspaceDashboardFunc(ctx, exec, workspaceID, from, to)
}

// GetWorkspaceDashboardCalls gets all the calls that were made to GetWorkspaceDashboard.
// Check the length with:
//
//	len(mockedReportRepository.GetWorkspaceDashboardCalls())
func (mock *ReportRepositoryMock) GetWorkspaceDashboardCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
	From        time.Time
	To          time.Time
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		From        time.Time
		To          time.Time
	}
	mock.lockGetWorkspaceDashboard.RLock()
	calls = mock.calls.GetWorkspaceDashboard
	mock.lockGetWorkspaceDashboard.RUnlock()
	return calls
}
