// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/google/uuid"
	"github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen"
	"github.com/o-ga09/vite-8-sample-app/internal/repository"
	"github.com/stephenafamo/bob"
	"sync"
	"time"
)

// Ensure, that TransactionRepositoryMock does implement repository.TransactionRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.TransactionRepository = &TransactionRepositoryMock{}

// TransactionRepositoryMock is a mock implementation of repository.TransactionRepository.
//
//	func TestSomethingThatUsesTransactionRepository(t *testing.T) {
//
//		// make and configure a mocked repository.TransactionRepository
//		mockedTransactionRepository := &TransactionRepositoryMock{
//			CreateFunc: func(ctx context.Context, exec bob.Executor, setter *dbgen.TransactionSetter) (*dbgen.Transaction, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID) (*dbgen.Transaction, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID) (dbgen.TransactionSlice, error) {
//				panic("mock out the List method")
//			},
//			ListByPeriodFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) (dbgen.TransactionSlice, error) {
//				panic("mock out the ListByPeriod method")
//			},
//			UpdateFunc: func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID, setter *dbgen.TransactionSetter) (*dbgen.Transaction, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedTransactionRepository in code that requires repository.TransactionRepository
//		// and then make assertions.
//
//	}
type TransactionRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, exec bob.Executor, setter *dbgen.TransactionSetter) (*dbgen.Transaction, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID) (*dbgen.Transaction, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID) (dbgen.TransactionSlice, error)

	// ListByPeriodFunc mocks the ListByPeriod method.
	ListByPeriodFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) (dbgen.TransactionSlice, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID, setter *dbgen.TransactionSetter) (*dbgen.Transaction, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// Setter is the setter argument value.
			Setter *dbgen.TransactionSetter
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
			// ID is the id argument value.
			ID uuid.UUID
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
		}
		// ListByPeriod holds details about calls to the ListByPeriod method.
		ListByPeriod []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID uuid.UUID
			// ID is the id argument value.
			ID uuid.UUID
			// Setter is the setter argument value.
			Setter *dbgen.TransactionSetter
		}
	}
	lockCreate       sync.RWMutex
	lockDelete       sync.RWMutex
	lockGet          sync.RWMutex
	lockList         sync.RWMutex
	lockListByPeriod sync.RWMutex
	lockUpdate       sync.RWMutex
}

// Create calls CreateFunc.
func (mock *TransactionRepositoryMock) Create(ctx context.Context, exec bob.Executor, setter *dbgen.TransactionSetter) (*dbgen.Transaction, error) {
	if mock.CreateFunc == nil {
		panic("TransactionRepositoryMock.CreateFunc: method is nil but TransactionRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Exec   bob.Executor
		Setter *dbgen.TransactionSetter
	}{
		Ctx:    ctx,
		Exec:   exec,
		Setter: setter,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, exec, setter)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedTransactionRepository.CreateCalls())
func (mock *TransactionRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Exec   bob.Executor
	Setter *dbgen.TransactionSetter
} {
	var calls []struct {
		Ctx    context.Context
		Exec   bob.Executor
		Setter *dbgen.TransactionSetter
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *TransactionRepositoryMock) Delete(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("TransactionRepositoryMock.DeleteFunc: method is nil but TransactionRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		ID          uuid.UUID
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
		ID:          id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, exec, workspaceID, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedTransactionRepository.DeleteCalls())
func (mock *TransactionRepositoryMock) DeleteCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
	ID          uuid.UUID
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		ID          uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *TransactionRepositoryMock) Get(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID) (*dbgen.Transaction, error) {
	if mock.GetFunc == nil {
		panic("TransactionRepositoryMock.GetFunc: method is nil but TransactionRepository.Get was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		ID          uuid.UUID
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
		ID:          id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, exec, workspaceID, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedTransactionRepository.GetCalls())
func (mock *TransactionRepositoryMock) GetCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
	ID          uuid.UUID
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		ID          uuid.UUID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *TransactionRepositoryMock) List(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID) (dbgen.TransactionSlice, error) {
	if mock.ListFunc == nil {
		panic("TransactionRepositoryMock.ListFunc: method is nil but TransactionRepository.List was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, exec, workspaceID)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedTransactionRepository.ListCalls())
func (mock *TransactionRepositoryMock) ListCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListByPeriod calls ListByPeriodFunc.
func (mock *TransactionRepositoryMock) ListByPeriod(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, from time.Time, to time.Time) (dbgen.TransactionSlice, error) {
	if mock.ListByPeriodFunc == nil {
		panic("TransactionRepositoryMock.ListByPeriodFunc: method is nil but TransactionRepository.ListByPeriod was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		From        time.Time
		To          time.Time
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
		From:        from,
		To:          to,
	}
	mock.lockListByPeriod.Lock()
	mock.calls.ListByPeriod = append(mock.calls.ListByPeriod, callInfo)
	mock.lockListByPeriod.Unlock()
	return mock.ListByPeriodFunc(ctx, exec, workspaceID, from, to)
}

// ListByPeriodCalls gets all the calls that were made to ListByPeriod.
// Check the length with:
//
//	len(mockedTransactionRepository.ListByPeriodCalls())
func (mock *TransactionRepositoryMock) ListByPeriodCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
	From        time.Time
	To          time.Time
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		From        time.Time
		To          time.Time
	}
	mock.lockListByPeriod.RLock()
	calls = mock.calls.ListByPeriod
	mock.lockListByPeriod.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *TransactionRepositoryMock) Update(ctx context.Context, exec bob.Executor, workspaceID uuid.UUID, id uuid.UUID, setter *dbgen.TransactionSetter) (*dbgen.Transaction, error) {
	if mock.UpdateFunc == nil {
		panic("TransactionRepositoryMock.UpdateFunc: method is nil but TransactionRepository.Update was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		ID          uuid.UUID
		Setter      *dbgen.TransactionSetter
	}{
		Ctx:         ctx,
		Exec:        exec,
		WorkspaceID: workspaceID,
		ID:          id,
		Setter:      setter,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, exec, workspaceID, id, setter)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedTransactionRepository.UpdateCalls())
func (mock *TransactionRepositoryMock) UpdateCalls() []struct {
	Ctx         context.Context
	Exec        bob.Executor
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	Setter      *dbgen.TransactionSetter
} {
	var calls []struct {
		Ctx         context.Context
		Exec        bob.Executor
		WorkspaceID uuid.UUID
		ID          uuid.UUID
		Setter      *dbgen.TransactionSetter
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
