// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/google/uuid"
	"github.com/o-ga09/vite-8-sample-app/internal/infra/dbgen"
	"github.com/o-ga09/vite-8-sample-app/internal/repository"
	"github.com/stephenafamo/bob"
	"sync"
)

// Ensure, that WorkspaceRepositoryMock does implement repository.WorkspaceRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.WorkspaceRepository = &WorkspaceRepositoryMock{}

// WorkspaceRepositoryMock is a mock implementation of repository.WorkspaceRepository.
//
//	func TestSomethingThatUsesWorkspaceRepository(t *testing.T) {
//
//		// make and configure a mocked repository.WorkspaceRepository
//		mockedWorkspaceRepository := &WorkspaceRepositoryMock{
//			CreateFunc: func(ctx context.Context, exec bob.Executor, setter *dbgen.WorkspaceSetter) (*dbgen.Workspace, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, exec bob.Executor, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, exec bob.Executor, id uuid.UUID) (*dbgen.Workspace, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, exec bob.Executor) (dbgen.WorkspaceSlice, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, exec bob.Executor, id uuid.UUID, setter *dbgen.WorkspaceSetter) (*dbgen.Workspace, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedWorkspaceRepository in code that requires repository.WorkspaceRepository
//		// and then make assertions.
//
//	}
type WorkspaceRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, exec bob.Executor, setter *dbgen.WorkspaceSetter) (*dbgen.Workspace, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, exec bob.Executor, id uuid.UUID) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, exec bob.Executor, id uuid.UUID) (*dbgen.Workspace, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, exec bob.Executor) (dbgen.WorkspaceSlice, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, exec bob.Executor, id uuid.UUID, setter *dbgen.WorkspaceSetter) (*dbgen.Workspace, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// Setter is the setter argument value.
			Setter *dbgen.WorkspaceSetter
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// ID is the id argument value.
			ID uuid.UUID
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Exec is the exec argument value.
			Exec bob.Executor
			// ID is the id argument value.
			ID uuid.UUID
			// Setter is the setter argument value.
			Setter *dbgen.WorkspaceSetter
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *WorkspaceRepositoryMock) Create(ctx context.Context, exec bob.Executor, setter *dbgen.WorkspaceSetter) (*dbgen.Workspace, error) {
	if mock.CreateFunc == nil {
		panic("WorkspaceRepositoryMock.CreateFunc: method is nil but WorkspaceRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Exec   bob.Executor
		Setter *dbgen.WorkspaceSetter
	}{
		Ctx:    ctx,
		Exec:   exec,
		Setter: setter,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, exec, setter)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedWorkspaceRepository.CreateCalls())
func (mock *WorkspaceRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Exec   bob.Executor
	Setter *dbgen.WorkspaceSetter
} {
	var calls []struct {
		Ctx    context.Context
		Exec   bob.Executor
		Setter *dbgen.WorkspaceSetter
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *WorkspaceRepositoryMock) Delete(ctx context.Context, exec bob.Executor, id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("WorkspaceRepositoryMock.DeleteFunc: method is nil but WorkspaceRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Exec bob.Executor
		ID   uuid.UUID
	}{
		Ctx:  ctx,
		Exec: exec,
		ID:   id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, exec, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedWorkspaceRepository.DeleteCalls())
func (mock *WorkspaceRepositoryMock) DeleteCalls() []struct {
	Ctx  context.Context
	Exec bob.Executor
	ID   uuid.UUID
} {
	var calls []struct {
		Ctx  context.Context
		Exec bob.Executor
		ID   uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *WorkspaceRepositoryMock) Get(ctx context.Context, exec bob.Executor, id uuid.UUID) (*dbgen.Workspace, error) {
	if mock.GetFunc == nil {
		panic("WorkspaceRepositoryMock.GetFunc: method is nil but WorkspaceRepository.Get was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Exec bob.Executor
		ID   uuid.UUID
	}{
		Ctx:  ctx,
		Exec: exec,
		ID:   id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, exec, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedWorkspaceRepository.GetCalls())
func (mock *WorkspaceRepositoryMock) GetCalls() []struct {
	Ctx  context.Context
	Exec bob.Executor
	ID   uuid.UUID
} {
	var calls []struct {
		Ctx  context.Context
		Exec bob.Executor
		ID   uuid.UUID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *WorkspaceRepositoryMock) List(ctx context.Context, exec bob.Executor) (dbgen.WorkspaceSlice, error) {
	if mock.ListFunc == nil {
		panic("WorkspaceRepositoryMock.ListFunc: method is nil but WorkspaceRepository.List was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Exec bob.Executor
	}{
		Ctx:  ctx,
		Exec: exec,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, exec)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedWorkspaceRepository.ListCalls())
func (mock *WorkspaceRepositoryMock) ListCalls() []struct {
	Ctx  context.Context
	Exec bob.Executor
} {
	var calls []struct {
		Ctx  context.Context
		Exec bob.Executor
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *WorkspaceRepositoryMock) Update(ctx context.Context, exec bob.Executor, id uuid.UUID, setter *dbgen.WorkspaceSetter) (*dbgen.Workspace, error) {
	if mock.UpdateFunc == nil {
		panic("WorkspaceRepositoryMock.UpdateFunc: method is nil but WorkspaceRepository.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Exec   bob.Executor
		ID     uuid.UUID
		Setter *dbgen.WorkspaceSetter
	}{
		Ctx:    ctx,
		Exec:   exec,
		ID:     id,
		Setter: setter,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, exec, id, setter)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedWorkspaceRepository.UpdateCalls())
func (mock *WorkspaceRepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Exec   bob.Executor
	ID     uuid.UUID
	Setter *dbgen.WorkspaceSetter
} {
	var calls []struct {
		Ctx    context.Context
		Exec   bob.Executor
		ID     uuid.UUID
		Setter *dbgen.WorkspaceSetter
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
