// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AccountErrors = &accountErrors{
	ErrUniqueAccountsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "accounts",
		columns: []string{"id"},
		s:       "accounts_pkey",
	},

	ErrUniqueAccountsWorkspaceIdIdKey: &UniqueConstraintError{
		schema:  "",
		table:   "accounts",
		columns: []string{"workspace_id", "id"},
		s:       "accounts_workspace_id_id_key",
	},

	ErrUniqueAccountsWorkspaceIdNameKey: &UniqueConstraintError{
		schema:  "",
		table:   "accounts",
		columns: []string{"workspace_id", "name"},
		s:       "accounts_workspace_id_name_key",
	},
}

type accountErrors struct {
	ErrUniqueAccountsPkey *UniqueConstraintError

	ErrUniqueAccountsWorkspaceIdIdKey *UniqueConstraintError

	ErrUniqueAccountsWorkspaceIdNameKey *UniqueConstraintError
}
