// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CategoryErrors = &categoryErrors{
	ErrUniqueCategoriesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "categories",
		columns: []string{"id"},
		s:       "categories_pkey",
	},

	ErrUniqueCategoriesWorkspaceIdCategoryTypeNameKey: &UniqueConstraintError{
		schema:  "",
		table:   "categories",
		columns: []string{"workspace_id", "category_type", "name"},
		s:       "categories_workspace_id_category_type_name_key",
	},

	ErrUniqueCategoriesWorkspaceIdIdKey: &UniqueConstraintError{
		schema:  "",
		table:   "categories",
		columns: []string{"workspace_id", "id"},
		s:       "categories_workspace_id_id_key",
	},
}

type categoryErrors struct {
	ErrUniqueCategoriesPkey *UniqueConstraintError

	ErrUniqueCategoriesWorkspaceIdCategoryTypeNameKey *UniqueConstraintError

	ErrUniqueCategoriesWorkspaceIdIdKey *UniqueConstraintError
}
