// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TransactionErrors = &transactionErrors{
	ErrUniqueTransactionsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "transactions",
		columns: []string{"id"},
		s:       "transactions_pkey",
	},

	ErrUniqueTransactionsWorkspaceIdIdKey: &UniqueConstraintError{
		schema:  "",
		table:   "transactions",
		columns: []string{"workspace_id", "id"},
		s:       "transactions_workspace_id_id_key",
	},
}

type transactionErrors struct {
	ErrUniqueTransactionsPkey *UniqueConstraintError

	ErrUniqueTransactionsWorkspaceIdIdKey *UniqueConstraintError
}
