// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var WorkspaceErrors = &workspaceErrors{
	ErrUniqueWorkspacesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "workspaces",
		columns: []string{"id"},
		s:       "workspaces_pkey",
	},
}

type workspaceErrors struct {
	ErrUniqueWorkspacesPkey *UniqueConstraintError
}
