name: CI

on:
  pull_request:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.10.1
          working-directory: .
          args: --timeout=5m --config=./.golangci.yaml ./...

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: taskman
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/taskman?sslmode=disable
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: go mod download
      - run: go test ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go mod download
      - run: go build ./...

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.1
          node-version: 24

      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-setup-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('frontend/.npmrc') }}

      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          pnpm install

      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        name: Save node_modules cache
        uses: actions/cache/save@v3
        with:
          path: '**/node_modules'
          key: ${{ steps.node_modules_cache_id.outputs.cache-primary-key }}

      - run: pnpm run lint
      - run: pnpm run fmt
      - run: pnpm run test
